export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';

export const START_CHATROOM_LOADING = 'START_CHATROOM_LOADING';
export const STOP_CHATROOM_LOADING = 'STOP_CHATROOM_LOADING';