export const GET_HOMEFEED_CHAT = 'GET_HOMEFEED_CHAT';
export const GET_HOMEFEED_CHAT_SUCCESS = 'GET_HOMEFEED_CHAT_SUCCESS';
export const GET_HOMEFEED_CHAT_FAILED = 'GET_HOMEFEED_CHAT_FAILED';

export const UPDATE_HOMEFEED_CHAT = 'UPDATE_HOMEFEED_CHAT';
export const UPDATE_HOMEFEED_CHAT_SUCCESS = 'UPDATE_HOMEFEED_CHAT_SUCCESS';
export const UPDATE_HOMEFEED_CHAT_FAILED = 'UPDATE_HOMEFEED_CHAT_FAILED';

export const SET_PAGE = 'SET_PAGE';

export const INIT_API = 'INIT_API';
export const INIT_API_SUCCESS = 'INIT_API_SUCCESS';
export const INIT_API_FAILED = 'INIT_API_FAILED';

export const GET_EXPLORE_FEED_CHAT = 'GET_EXPLORE_FEED_CHAT';
export const GET_EXPLORE_FEED_CHAT_SUCCESS = 'GET_EXPLORE_FEED_CHAT_SUCCESS';
export const GET_EXPLORE_FEED_CHAT_FAILED = 'GET_EXPLORE_FEED_CHAT_FAILED';

export const UPDATE_EXPLORE_FEED_CHAT = 'UPDATE_EXPLORE_FEED_CHAT';
export const UPDATE_EXPLORE_FEED_CHAT_SUCCESS =
  'UPDATE_EXPLORE_FEED_CHAT_SUCCESS';
export const UPDATE_EXPLORE_FEED_CHAT_FAILED =
  'UPDATE_EXPLORE_FEED_CHAT_FAILED';

export const GET_CONVERSATIONS = 'GET_CONVERSATIONS';
export const GET_CONVERSATIONS_SUCCESS = 'GET_CONVERSATIONS_SUCCESS';
export const GET_CONVERSATIONS_FAILED = 'GET_CONVERSATIONS_FAILED';

export const PAGINATED_CONVERSATIONS = 'PAGINATED_CONVERSATIONS';
export const PAGINATED_CONVERSATIONS_SUCCESS =
  'PAGINATED_CONVERSATIONS_SUCCESS';
export const PAGINATED_CONVERSATIONS_FAILED = 'PAGINATED_CONVERSATIONS_FAILED';

export const GET_CHATROOM = 'GET_CHATROOM';
export const GET_CHATROOM_SUCCESS = 'GET_CHATROOM_SUCCESS';
export const GET_CHATROOM_FAILED = 'GET_CHATROOM_FAILED';

export const ON_CONVERSATIONS_CREATE = 'ON_CONVERSATIONS_CREATE';
export const ON_CONVERSATIONS_CREATE_SUCCESS =
  'ON_CONVERSATIONS_CREATE_SUCCESS';
export const ON_CONVERSATIONS_CREATE_FAILED = 'ON_CONVERSATIONS_CREATE_FAILED';

export const UPDATE_CONVERSATIONS = 'UPDATE_CONVERSATIONS';
