export const GET_HOMEFEED_CHAT = 'GET_HOMEFEED_CHAT'
export const GET_HOMEFEED_CHAT_SUCCESS = 'GET_HOMEFEED_CHAT_SUCCESS'
export const GET_HOMEFEED_CHAT_FAILED = 'GET_HOMEFEED_CHAT_FAILED'

export const GET_CONVERSATIONS = 'GET_CONVERSATIONS'
export const GET_CONVERSATIONS_SUCCESS = 'GET_CONVERSATIONS_SUCCESS'
export const GET_CONVERSATIONS_FAILED = 'GET_CONVERSATIONS_FAILED'

export const ON_CONVERSATIONS_CREATE = 'ON_CONVERSATIONS_CREATE'
export const ON_CONVERSATIONS_CREATE_SUCCESS = 'ON_CONVERSATIONS_CREATE_SUCCESS'
export const ON_CONVERSATIONS_CREATE_FAILED = 'ON_CONVERSATIONS_CREATE_FAILED'