import {Platform, StyleSheet} from 'react-native';
import STYLES from '../../constants/Styles';

export const styles = StyleSheet.create({
  itemContainer: {
    flexDirection: 'row',
    padding: STYLES.$PADDINGS.MEDIUM,
    alignItems: 'center',
    backgroundColor: STYLES.$COLORS.TERTIARY,
  },
  avatar: {
    width: STYLES.$AVATAR.WIDTH,
    height: STYLES.$AVATAR.HEIGHT,
    borderRadius: STYLES.$AVATAR.BORDER_RADIUS,
    marginRight: STYLES.$MARGINS.SMALL,
  },
  lockIcon: {
    width: 15,
    height: 15,
    resizeMode: 'contain',
    marginLeft: 10,
  },
  secretInviteIcons: {
    width: 15,
    height: 15,
    resizeMode: 'contain',
  },
  muteIcon: {
    width: 17,
    height: 17,
    resizeMode: 'contain',
    marginLeft: 10,
  },
  infoContainer: {
    flex: 1,
  },
  headerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  title: {
    fontSize: STYLES.$FONT_SIZES.XL,
    fontFamily: STYLES.$FONT_TYPES.BOLD,
    color: STYLES.$COLORS.PRIMARY,
    maxWidth: '80%',
  },
  time: {
    color: STYLES.$COLORS.MSG,
    fontSize: STYLES.$FONT_SIZES.SMALL,
    fontFamily: STYLES.$FONT_TYPES.LIGHT,
  },
  parentLastMessage: {
    color: STYLES.$COLORS.PRIMARY,
    fontSize: STYLES.$FONT_SIZES.MEDIUM,
    fontFamily: STYLES.$FONT_TYPES.LIGHT,
  },
  lastMessage: {
    color: STYLES.$COLORS.PRIMARY,
    fontSize: STYLES.$FONT_SIZES.MEDIUM,
    fontFamily: STYLES.$FONT_TYPES.LIGHT,
  },
  deletedMessage: {
    color: STYLES.$COLORS.PRIMARY,
    fontSize: STYLES.$FONT_SIZES.MEDIUM,
    fontFamily: STYLES.$FONT_TYPES.LIGHT,
    fontStyle: 'italic',
    width: '85%',
  },
  attachment_msg: {
    color: STYLES.$COLORS.PRIMARY,
    fontSize: STYLES.$FONT_SIZES.MEDIUM,
    fontFamily: STYLES.$FONT_TYPES.LIGHT,
    marginRight: 5,
    alignSelf: 'flex-end',
    marginBottom: Platform.OS === 'android' ? -3 : -1,
  },
  pinned: {
    width: 20,
    height: 20,
    backgroundColor: STYLES.$COLORS.PRIMARY,
    borderRadius: 10,
    position: 'absolute',
    top: 16,
    right: 16,
  },
  unreadCountContainer: {
    minWidth: 25,
    minHeight: 25,
    backgroundColor: STYLES.$COLORS.PRIMARY,
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    padding: 5,
    bottom: 16,
    right: 15,
  },
  unreadCount: {
    color: STYLES.$COLORS.TERTIARY,
    fontSize: STYLES.$FONT_SIZES.SMALL,
    fontFamily: STYLES.$FONT_TYPES.SEMI_BOLD,
    marginTop: Platform.OS === 'ios' ? 2 : -1,
  },
  inviteIcon: {
    height: 40,
    width: 40,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderRadius: 50,
    borderColor: 'grey',
  },
  dmAvatarBubble: {
    backgroundColor: STYLES.$COLORS.SECONDARY,
    height: 25,
    width: 25,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    bottom: -2,
    right: 5,
  },
  dmAvatarBubbleImg: {
    height: 13,
    width: 13,
    resizeMode: 'contain',
  },
  alignCenter: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-end',
  },
  icon: {
    height: 15,
    width: 15,
    resizeMode: 'contain',
    marginRight: 5,
  },
});
