export const GET_HOMEFEED_CHAT = 'GET_HOMEFEED_CHAT';
export const GET_HOMEFEED_CHAT_SUCCESS = 'GET_HOMEFEED_CHAT_SUCCESS';
export const GET_HOMEFEED_CHAT_FAILED = 'GET_HOMEFEED_CHAT_FAILED';

export const GET_DMFEED_CHAT = 'GET_DMFEED_CHAT';
export const GET_DMFEED_CHAT_SUCCESS = 'GET_DMFEED_CHAT_SUCCESS';
export const GET_DMFEED_CHAT_FAILED = 'GET_DMFEED_CHAT_FAILED';

export const UPDATE_HOMEFEED_CHAT = 'UPDATE_HOMEFEED_CHAT';
export const UPDATE_HOMEFEED_CHAT_SUCCESS = 'UPDATE_HOMEFEED_CHAT_SUCCESS';
export const UPDATE_HOMEFEED_CHAT_FAILED = 'UPDATE_HOMEFEED_CHAT_FAILED';

export const UPDATE_DMFEED_CHAT = 'UPDATE_DMFEED_CHAT';
export const UPDATE_DMFEED_CHAT_SUCCESS = 'UPDATE_DMFEED_CHAT_SUCCESS';
export const UPDATE_DMFEED_CHAT_FAILED = 'UPDATE_DMFEED_CHAT_FAILED';

export const GET_INVITES = 'GET_INVITES';
export const GET_INVITES_SUCCESS = 'GET_INVITES_SUCCESS';
export const GET_INVITES_FAILED = 'GET_INVITES_FAILED';

export const UPDATE_INVITES = 'UPDATE_INVITES';
export const UPDATE_INVITES_SUCCESS = 'UPDATE_INVITES_SUCCESS';
export const UPDATE_INVITES_FAILED = 'UPDATE_INVITES_FAILED';

export const ACCEPT_INVITE = 'ACCEPT_INVITE';
export const ACCEPT_INVITE_SUCCESS = 'ACCEPT_INVITE_SUCCESS';
export const ACCEPT_INVITE_FAILED = 'ACCEPT_INVITE_FAILED';

export const REJECT_INVITE = 'REJECT_INVITE';
export const REJECT_INVITE_SUCCESS = 'REJECT_INVITE_SUCCESS';
export const REJECT_INVITE_FAILED = 'REJECT_INVITE_FAILED';

export const SET_PAGE = 'SET_PAGE';
export const SET_DM_PAGE = 'SET_DM_PAGE';
export const SHOW_TOAST = 'SHOW_TOAST';
export const EMPTY_BLOCK_DELETION = 'EMPTY_BLOCK_DELETION';
export const SET_CHATROOM_CREATOR = 'SET_CHATROOM_CREATOR';
export const SET_CHATROOM_TOPIC = 'SET_CHATROOM_TOPIC';
export const SET_TEMP_STATE_MESSAGE = 'SET_TEMP_STATE_MESSAGE';
export const CLEAR_CHATROOM_TOPIC = 'CLEAR_CHATROOM_TOPIC';

export const STATUS_BAR_STYLE = 'STATUS_BAR_STYLE';

export const CLEAR_CHATROOM_CONVERSATION = 'CLEAR_CHATROOM_CONVERSATION';
export const CLEAR_CHATROOM_DETAILS = 'CLEAR_CHATROOM_DETAILS';

export const INIT_API = 'INIT_API';
export const INIT_API_SUCCESS = 'INIT_API_SUCCESS';
export const INIT_API_FAILED = 'INIT_API_FAILED';

export const STORE_MY_CLIENT = 'STORE_MY_CLIENT';

export const PROFILE_DATA = 'PROFILE_DATA';
export const PROFILE_DATA_SUCCESS = 'PROFILE_DATA_SUCCESS';
export const GET_SYNC_HOMEFEED_CHAT_SUCCESS = 'GET_SYNC_HOMEFEED_CHAT_SUCCESS';
export const TO_BE_DELETED = 'TO_BE_DELETED';
export const PROFILE_DATA_FAILED = 'PROFILE_DATA_FAILED';
export const PAGINATED_CONVERSATIONS_START_SUCCESS =
  'PAGINATED_CONVERSATIONS_START_SUCCESS';

export const GET_EXPLORE_FEED_CHAT = 'GET_EXPLORE_FEED_CHAT';
export const GET_EXPLORE_FEED_CHAT_SUCCESS = 'GET_EXPLORE_FEED_CHAT_SUCCESS';
export const GET_EXPLORE_FEED_CHAT_FAILED = 'GET_EXPLORE_FEED_CHAT_FAILED';

export const SET_EXPLORE_FEED_PAGE = 'SET_EXPLORE_FEED_PAGE';

export const UPDATE_EXPLORE_FEED_CHAT = 'UPDATE_EXPLORE_FEED_CHAT';
export const UPDATE_EXPLORE_FEED_CHAT_SUCCESS =
  'UPDATE_EXPLORE_FEED_CHAT_SUCCESS';
export const UPDATE_EXPLORE_FEED_CHAT_FAILED =
  'UPDATE_EXPLORE_FEED_CHAT_FAILED';

export const GET_CONVERSATIONS = 'GET_CONVERSATIONS';
export const GET_CONVERSATIONS_SUCCESS = 'GET_CONVERSATIONS_SUCCESS';
export const GET_CONVERSATIONS_FAILED = 'GET_CONVERSATIONS_FAILED';

export const LONG_PRESSED = 'LONG_PRESSED';
export const SELECTED_MESSAGES = 'SELECTED_MESSAGES';
export const CLEAR_SELECTED_MESSAGES = 'CLEAR_SELECTED_MESSAGES';

export const PAGINATED_CONVERSATIONS = 'PAGINATED_CONVERSATIONS';
export const PAGINATED_CONVERSATIONS_END_SUCCESS =
  'PAGINATED_CONVERSATIONS_END_SUCCESS';
export const PAGINATED_CONVERSATIONS_FAILED = 'PAGINATED_CONVERSATIONS_FAILED';

export const FIREBASE_CONVERSATIONS = 'FIREBASE_CONVERSATIONS';
export const FIREBASE_CONVERSATIONS_SUCCESS = 'FIREBASE_CONVERSATIONS_SUCCESS';
export const GET_CHATROOM_DB_SUCCESS = 'GET_CHATROOM_DB_SUCCESS';
export const ADD_STATE_MESSAGE = 'ADD_STATE_MESSAGE';
export const FIREBASE_CONVERSATIONS_FAILED = 'FIREBASE_CONVERSATIONS_FAILED';

export const GET_CHATROOM = 'GET_CHATROOM';
export const GET_CHATROOM_SUCCESS = 'GET_CHATROOM_SUCCESS';
export const GET_CHATROOM_ACTIONS_SUCCESS = 'GET_CHATROOM_ACTIONS_SUCCESS';
export const GET_CHATROOM_FAILED = 'GET_CHATROOM_FAILED';

export const ON_CONVERSATIONS_CREATE = 'ON_CONVERSATIONS_CREATE';
export const ON_CONVERSATIONS_CREATE_SUCCESS =
  'ON_CONVERSATIONS_CREATE_SUCCESS';
export const ON_CONVERSATIONS_CREATE_FAILED = 'ON_CONVERSATIONS_CREATE_FAILED';
export const PAGINATED_CONVERSATIONS_SUCCESS =
  'PAGINATED_CONVERSATIONS_SUCCESS';

export const UPDATE_CONVERSATIONS = 'UPDATE_CONVERSATIONS';
export const EDIT_CONVERSATION = 'EDIT_CONVERSATION';
export const UPDATE_LAST_CONVERSATION = 'UPDATE_LAST_CONVERSATION';
export const SET_INITIAL_GROUPFEED_CHATROOM = 'SET_INITIAL_GROUPFEED_CHATROOM';
export const UPDATE_GROUPFEED_CHATROOM = 'UPDATE_GROUPFEED_CHATROOM';
export const DELETE_GROUPFEED_CHATROOM = 'DELETE_GROUPFEED_CHATROOM';
export const DELETE_DMFEED_CHATROOM = 'DELETE_DMFEED_CHATROOM';
export const SET_INITIAL_DMFEED_CHATROOM = 'SET_INITIAL_DMFEED_CHATROOM';
export const UPDATE_DMFEED_CHATROOM = 'UPDATE_DMFEED_CHATROOM';
export const INSERT_GROUPFEED_CHATROOM = 'INSERT_GROUPFEED_CHATROOM';
export const INSERT_DMFEED_CHATROOM = 'INSERT_DMFEED_CHATROOM';
export const UPDATE_MULTIMEDIA_CONVERSATIONS =
  'UPDATE_MULTIMEDIA_CONVERSATIONS';
export const MESSAGE_SENT = 'MESSAGE_SENT';
export const REACTION_SENT = 'REACTION_SENT';
export const SET_POSITION = 'SET_POSITION';

export const UPDATE_CHAT_REQUEST_STATE = 'UPDATE_CHAT_REQUEST_STATE';

export const SELECTED_FILES_TO_UPLOAD = 'SELECTED_FILES_TO_UPLOAD';
export const SELECTED_VOICE_NOTE_FILES_TO_UPLOAD =
  'SELECTED_VOICE_NOTE_FILES_TO_UPLOAD';
export const SELECTED_FILE_TO_VIEW = 'SELECTED_FILE_TO_VIEW';
export const SELECTED_MORE_FILES_TO_UPLOAD = 'SELECTED_MORE_FILES_TO_UPLOAD';
export const CLEAR_SELECTED_FILES_TO_UPLOAD = 'CLEAR_SELECTED_FILES_TO_UPLOAD';
export const CLEAR_SELECTED_VOICE_NOTE_FILES_TO_UPLOAD =
  'CLEAR_SELECTED_VOICE_NOTE_FILES_TO_UPLOAD';
export const CLEAR_SELECTED_FILE_TO_VIEW = 'CLEAR_SELECTED_FILE_TO_VIEW';
export const IS_FILE_UPLOADING = 'IS_FILE_UPLOADING';
export const SET_FILE_UPLOADING_MESSAGES = 'SET_FILE_UPLOADING_MESSAGES';
export const CLEAR_FILE_UPLOADING_MESSAGES = 'CLEAR_FILE_UPLOADING_MESSAGES';
export const UPDATE_FILE_UPLOADING_OBJECT = 'UPDATE_FILE_UPLOADING_OBJECT';
export const SELECTED_FILES_TO_UPLOAD_THUMBNAILS =
  'SELECTED_FILES_TO_UPLOAD_THUMBNAILS';
export const SET_IS_REPLY = 'SET_IS_REPLY';
export const SET_REPLY_MESSAGE = 'SET_REPLY_MESSAGE';
export const SET_EDIT_MESSAGE = 'SET_EDIT_MESSAGE';
export const FILE_SENT = 'FILE_SENT';
