export const conversationData = {
  success: true,
  data: {
    conversations: [
      {
        // answer:
        //   'This is the very beginning of your direct message with <<Ankit SDK 1|route://member/86975>> <<Ankit|route://member/86986>>',
        answer:
          'This is the very <<Ankit|route://member/86986>> beginning of your direct message with ',
        attachment_count: 0,
        attachments_uploaded: false,
        chatroom_id: 70185,
        community_id: 50421,
        created_at: '22:58',
        created_epoch: 1672334922954,
        date: '29 Dec 2022',
        has_files: false,
        id: 239301,
        is_edited: false,
        member: {
          custom_intro_text: 'Created this community on 28 Dec 2022',
          custom_title: 'Community Manager',
          id: 86975,
          image_url: '',
          is_guest: false,
          is_owner: false,
          member_since: 'Member since Dec 28 2022',
          member_since_epoch: 1672224031,
          name: 'Ankit SDK 1',
          organisation_name: null,
          route:
            'route://member_community_profile?community_id=50421&member_id=86975',
          state: 1,
          updated_at: 1672224031,
          user_unique_id: '780cfe5e-1605-49ee-b8a0-c79deaaf77bf',
        },
        reactions: [],
        state: 1,
      },
      {
        answer: 'Hey',
        attachment_count: 0,
        attachments_uploaded: false,
        chatroom_id: 70185,
        community_id: 50421,
        created_at: '15:16',
        created_epoch: 1676022360719,
        date: '10 Feb 2023',
        has_files: false,
        id: 244994,
        is_edited: false,
        member: {
          id: 86986,
          image_url: '',
          is_guest: false,
          is_owner: false,
          member_since: 'Member since Dec 29 2022',
          member_since_epoch: 1672323882,
          name: 'Ankit',
          organisation_name: null,
          route:
            'route://member_community_profile?community_id=50421&member_id=86986',
          state: 4,
          updated_at: 1672323882,
          user_unique_id: '0992885d-a170-494b-80c5-ecaef0cb2a24',
        },
        reactions: [
          {
            member: {
              id: 86986,
              image_url: '',
              name: 'Ankit',
            },
            reaction: '🤩',
            updated_at: 1676023076384,
          },
        ],
        state: 0,
      },
      {
        answer: '1',
        attachment_count: 0,
        attachments_uploaded: false,
        chatroom_id: 70185,
        community_id: 50421,
        created_at: '15:26',
        created_epoch: 1676022963383,
        date: '10 Feb 2023',
        has_files: false,
        id: 244995,
        is_edited: false,
        member: {
          id: 86986,
          image_url: '',
          is_guest: false,
          is_owner: false,
          member_since: 'Member since Dec 29 2022',
          member_since_epoch: 1672323882,
          name: 'Ankit',
          organisation_name: null,
          route:
            'route://member_community_profile?community_id=50421&member_id=86986',
          state: 4,
          updated_at: 1672323882,
          user_unique_id: '0992885d-a170-494b-80c5-ecaef0cb2a24',
        },
        reactions: [],
        reply_conversation: 244994,
        reply_conversation_object: {
          // answer:
          //   'Hey skdjnksdjn ksjdnck sjdncks kj nds cksd ksdncksdn ksldncksdnj kjdflsdjs kndfsldkjn mc,zmxcz skldjflsdkjf skdnsld sdds sddsf cds sdsldk sdcs sd dc s ksdnkfnsdknf sldklskdjlod lskdjlksdjoweij lkedslm',
          answer: 'hey',
          attachment_count: 0,
          attachments_uploaded: false,
          chatroom_id: 70185,
          community_id: 50421,
          created_at: 1676022360719,
          created_epoch: 1676022360719,
          date: '10 Feb 2023',
          has_files: false,
          id: 244994,
          is_edited: false,
          member: {
            id: 86986,
            image_url: '',
            is_guest: false,
            is_owner: false,
            member_since: 'Member since Dec 29 2022',
            member_since_epoch: 1672323882,
            name: 'Ankit',
            organisation_name: null,
            route:
              'route://member_community_profile?community_id=50421&member_id=86986',
            state: 4,
            updated_at: 1672323882,
            user_unique_id: '0992885d-a170-494b-80c5-ecaef0cb2a24',
          },
          reactions: [
            {
              member: {
                id: 86986,
                image_url: '',
                name: 'Ankit',
              },
              reaction: '🤩',
              updated_at: 1676023076384,
            },
          ],
          state: 0,
        },
        state: 0,
      },
      {
        answer: '😅😅',
        attachment_count: 0,
        attachments_uploaded: false,
        chatroom_id: 70185,
        community_id: 50421,
        created_at: '15:26',
        created_epoch: 1676022975976,
        date: '10 Feb 2023',
        has_files: false,
        id: 244996,
        is_edited: false,
        member: {
          id: 86986,
          image_url: '',
          is_guest: false,
          is_owner: false,
          member_since: 'Member since Dec 29 2022',
          member_since_epoch: 1672323882,
          name: 'Ankit',
          organisation_name: null,
          route:
            'route://member_community_profile?community_id=50421&member_id=86986',
          state: 4,
          updated_at: 1672323882,
          user_unique_id: '0992885d-a170-494b-80c5-ecaef0cb2a24',
        },
        reactions: [],
        state: 0,
      },
      {
        answer: 'Happy!',
        attachment_count: 0,
        attachments_uploaded: false,
        chatroom_id: 70185,
        community_id: 50421,
        created_at: '15:26',
        created_epoch: 1676022982139,
        date: '10 Feb 2023',
        deleted_by: 86986,
        has_files: false,
        id: 244997,
        is_edited: false,
        member: {
          id: 86986,
          image_url: '',
          is_guest: false,
          is_owner: false,
          member_since: 'Member since Dec 29 2022',
          member_since_epoch: 1672323882,
          name: 'Ankit',
          organisation_name: null,
          route:
            'route://member_community_profile?community_id=50421&member_id=86986',
          state: 4,
          updated_at: 1672323882,
          user_unique_id: '0992885d-a170-494b-80c5-ecaef0cb2a24',
        },
        reactions: [],
        state: 0,
      },
      {
        answer: '',
        attachment_count: 1,
        attachments: [
          {
            index: 0,
            meta: {
              size: 48936,
            },
            name: 'cookie for you.jpeg',
            type: 'image',
            url: 'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70185/conversation/244998/cookie%20for%20you.jpeg',
          },
        ],
        attachments_uploaded: true,
        audios: [],
        chatroom_id: 70185,
        community_id: 50421,
        created_at: '15:27',
        created_epoch: 1676023020979,
        date: '10 Feb 2023',
        has_files: true,
        id: 244998,
        images: [
          {
            image_url:
              'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70185/conversation/244998/cookie%20for%20you.jpeg',
            index: 0,
            meta: {
              size: 48936,
            },
            name: 'cookie for you.jpeg',
            type: 'image',
          },
        ],
        is_edited: false,
        member: {
          id: 86986,
          image_url: '',
          is_guest: false,
          is_owner: false,
          member_since: 'Member since Dec 29 2022',
          member_since_epoch: 1672323882,
          name: 'Ankit',
          organisation_name: null,
          route:
            'route://member_community_profile?community_id=50421&member_id=86986',
          state: 4,
          updated_at: 1672323882,
          user_unique_id: '0992885d-a170-494b-80c5-ecaef0cb2a24',
        },
        pdf: [],
        reactions: [],
        state: 0,
        videos: [],
      },
      {
        answer: '',
        attachment_count: 1,
        attachments: [
          {
            index: 0,
            meta: {
              size: 1682818,
            },
            name: 'WhatsApp Video 2023-01-24 at 3.10.21 PM.mp4',
            type: 'video',
            url: 'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70185/conversation/244999/WhatsApp%20Video%202023-01-24%20at%203.10.21%20PM.mp4',
          },
        ],
        attachments_uploaded: true,
        audios: [],
        chatroom_id: 70185,
        community_id: 50421,
        created_at: '15:27',
        created_epoch: 1676023037249,
        date: '10 Feb 2023',
        has_files: true,
        id: 244999,
        images: [],
        is_edited: false,
        member: {
          id: 86986,
          image_url: '',
          is_guest: false,
          is_owner: false,
          member_since: 'Member since Dec 29 2022',
          member_since_epoch: 1672323882,
          name: 'Ankit',
          organisation_name: null,
          route:
            'route://member_community_profile?community_id=50421&member_id=86986',
          state: 4,
          updated_at: 1672323882,
          user_unique_id: '0992885d-a170-494b-80c5-ecaef0cb2a24',
        },
        pdf: [],
        reactions: [],
        state: 0,
        videos: [
          {
            index: 0,
            meta: {
              size: 1682818,
            },
            name: 'WhatsApp Video 2023-01-24 at 3.10.21 PM.mp4',
            type: 'video',
            video_url:
              'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70185/conversation/244999/WhatsApp%20Video%202023-01-24%20at%203.10.21%20PM.mp4',
          },
        ],
      },
      {
        answer: '',
        attachment_count: 1,
        attachments: [
          {
            index: 0,
            meta: {
              size: 12917556,
            },
            name: 'SignalPresentation.pdf',
            type: 'pdf',
            url: 'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70185/conversation/245000/SignalPresentation.pdf',
          },
        ],
        attachments_uploaded: true,
        audios: [],
        chatroom_id: 70185,
        community_id: 50421,
        created_at: '15:27',
        created_epoch: 1676023050882,
        date: '10 Feb 2023',
        has_files: true,
        id: 245000,
        images: [],
        is_edited: false,
        last_seen: true,
        member: {
          id: 86986,
          image_url: '',
          is_guest: false,
          is_owner: false,
          member_since: 'Member since Dec 29 2022',
          member_since_epoch: 1672323882,
          name: 'Ankit',
          organisation_name: null,
          route:
            'route://member_community_profile?community_id=50421&member_id=86986',
          state: 4,
          updated_at: 1672323882,
          user_unique_id: '0992885d-a170-494b-80c5-ecaef0cb2a24',
        },
        pdf: [
          {
            index: 0,
            meta: {
              size: 12917556,
            },
            name: 'SignalPresentation.pdf',
            pdf_file:
              'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70185/conversation/245000/SignalPresentation.pdf',
            type: 'pdf',
          },
        ],
        reactions: [],
        state: 0,
        videos: [],
      },
      {
        answer: '',
        attachment_count: 5,
        attachments: [
          {
            index: 0,
            meta: {
              size: 1789,
            },
            name: 'back_arrow3x.png',
            type: 'image',
            url: 'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246659/back_arrow3x.png',
          },
          {
            index: 1,
            meta: {
              size: 1225,
            },
            name: 'camera_icon3x.png',
            type: 'image',
            url: 'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246659/camera_icon3x.png',
          },
          {
            index: 2,
            meta: {
              size: 490,
            },
            name: 'cross_icon3x.png',
            type: 'image',
            url: 'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246659/cross_icon3x.png',
          },
          {
            index: 3,
            meta: {
              size: 430,
            },
            name: 'document_icon3x.png',
            type: 'image',
            url: 'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246659/document_icon3x.png',
          },
          {
            index: 4,
            meta: {
              size: 521,
            },
            name: 'down_arrow3x.png',
            type: 'image',
            url: 'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246659/down_arrow3x.png',
          },
        ],
        attachments_uploaded: true,
        audios: [],
        chatroom_id: 70716,
        community_id: 50421,
        created_at: '16:34',
        created_epoch: 1676372670694,
        date: '14 Feb 2023',
        has_files: true,
        id: 246659,
        images: [
          {
            image_url:
              'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246659/back_arrow3x.png',
            index: 0,
            meta: {
              size: 1789,
            },
            name: 'back_arrow3x.png',
            type: 'image',
          },
          {
            image_url:
              'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246659/camera_icon3x.png',
            index: 1,
            meta: {
              size: 1225,
            },
            name: 'camera_icon3x.png',
            type: 'image',
          },
          {
            image_url:
              'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246659/cross_icon3x.png',
            index: 2,
            meta: {
              size: 490,
            },
            name: 'cross_icon3x.png',
            type: 'image',
          },
          {
            image_url:
              'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246659/document_icon3x.png',
            index: 3,
            meta: {
              size: 430,
            },
            name: 'document_icon3x.png',
            type: 'image',
          },
          {
            image_url:
              'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246659/down_arrow3x.png',
            index: 4,
            meta: {
              size: 521,
            },
            name: 'down_arrow3x.png',
            type: 'image',
          },
        ],
        is_edited: false,
        member: {
          id: 87040,
          image_url: '',
          is_guest: false,
          is_owner: false,
          member_since: 'Member since Jan 05 2023',
          member_since_epoch: 1672910682,
          name: 'USERONE',
          organisation_name: null,
          route:
            'route://member_community_profile?community_id=50421&member_id=87040',
          state: 4,
          updated_at: 1672910682,
          user_unique_id: '3cdcaf10-1950-4997-b48e-7a29bbe3dcdc',
        },
        pdf: [],
        reactions: [],
        state: 0,
        videos: [],
      },
      {
        answer: 'Hey',
        attachment_count: 0,
        attachments_uploaded: false,
        chatroom_id: 70716,
        community_id: 50421,
        created_at: '16:40',
        created_epoch: 1676373037797,
        date: '14 Feb 2023',
        has_files: false,
        id: 246662,
        is_edited: false,
        member: {
          id: 87040,
          image_url: '',
          is_guest: false,
          is_owner: false,
          member_since: 'Member since Jan 05 2023',
          member_since_epoch: 1672910682,
          name: 'USERONE',
          organisation_name: null,
          route:
            'route://member_community_profile?community_id=50421&member_id=87040',
          state: 4,
          updated_at: 1672910682,
          user_unique_id: '3cdcaf10-1950-4997-b48e-7a29bbe3dcdc',
        },
        reactions: [],
        state: 0,
      },
      {
        answer: 'Multiple images reply',
        attachment_count: 0,
        attachments_uploaded: false,
        chatroom_id: 70716,
        community_id: 50421,
        created_at: '16:47',
        created_epoch: 1676373450603,
        date: '14 Feb 2023',
        has_files: false,
        id: 246679,
        is_edited: false,
        member: {
          id: 87040,
          image_url: '',
          is_guest: false,
          is_owner: false,
          member_since: 'Member since Jan 05 2023',
          member_since_epoch: 1672910682,
          name: 'USERONE',
          organisation_name: null,
          route:
            'route://member_community_profile?community_id=50421&member_id=87040',
          state: 4,
          updated_at: 1672910682,
          user_unique_id: '3cdcaf10-1950-4997-b48e-7a29bbe3dcdc',
        },
        reactions: [],
        reply_conversation: 246659,
        reply_conversation_object: {
          answer: '',
          attachment_count: 5,
          attachments: [
            {
              index: 0,
              meta: {
                size: 1789,
              },
              name: 'back_arrow3x.png',
              type: 'image',
              url: 'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246659/back_arrow3x.png',
            },
            {
              index: 1,
              meta: {
                size: 1225,
              },
              name: 'camera_icon3x.png',
              type: 'image',
              url: 'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246659/camera_icon3x.png',
            },
            {
              index: 2,
              meta: {
                size: 490,
              },
              name: 'cross_icon3x.png',
              type: 'image',
              url: 'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246659/cross_icon3x.png',
            },
            {
              index: 3,
              meta: {
                size: 430,
              },
              name: 'document_icon3x.png',
              type: 'image',
              url: 'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246659/document_icon3x.png',
            },
            {
              index: 4,
              meta: {
                size: 521,
              },
              name: 'down_arrow3x.png',
              type: 'image',
              url: 'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246659/down_arrow3x.png',
            },
          ],
          attachments_uploaded: true,
          audios: [],
          chatroom_id: 70716,
          community_id: 50421,
          created_at: 1676372670694,
          created_epoch: 1676372670694,
          date: '14 Feb 2023',
          has_files: true,
          id: 246659,
          images: [
            {
              image_url:
                'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246659/back_arrow3x.png',
              index: 0,
              meta: {
                size: 1789,
              },
              name: 'back_arrow3x.png',
              type: 'image',
            },
            {
              image_url:
                'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246659/camera_icon3x.png',
              index: 1,
              meta: {
                size: 1225,
              },
              name: 'camera_icon3x.png',
              type: 'image',
            },
            {
              image_url:
                'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246659/cross_icon3x.png',
              index: 2,
              meta: {
                size: 490,
              },
              name: 'cross_icon3x.png',
              type: 'image',
            },
            {
              image_url:
                'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246659/document_icon3x.png',
              index: 3,
              meta: {
                size: 430,
              },
              name: 'document_icon3x.png',
              type: 'image',
            },
            {
              image_url:
                'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246659/down_arrow3x.png',
              index: 4,
              meta: {
                size: 521,
              },
              name: 'down_arrow3x.png',
              type: 'image',
            },
          ],
          is_edited: false,
          member: {
            id: 87040,
            image_url: '',
            is_guest: false,
            is_owner: false,
            member_since: 'Member since Jan 05 2023',
            member_since_epoch: 1672910682,
            name: 'USERONE',
            organisation_name: null,
            route:
              'route://member_community_profile?community_id=50421&member_id=87040',
            state: 4,
            updated_at: 1672910682,
            user_unique_id: '3cdcaf10-1950-4997-b48e-7a29bbe3dcdc',
          },
          pdf: [],
          reactions: [],
          state: 0,
          videos: [],
        },
        state: 0,
      },
      {
        answer: '',
        attachment_count: 4,
        attachments: [
          {
            index: 0,
            meta: {
              size: 12917556,
            },
            name: 'SignalPresentation.pdf',
            type: 'pdf',
            url: 'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246683/SignalPresentation.pdf',
          },
          {
            index: 1,
            meta: {
              size: 12917556,
            },
            name: 'SignalPresentation copy.pdf',
            type: 'pdf',
            url: 'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246683/SignalPresentation+copy.pdf',
          },
          {
            index: 2,
            meta: {
              size: 12917556,
            },
            name: 'SignalPresentation copy 2.pdf',
            type: 'pdf',
            url: 'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246683/SignalPresentation+copy+2.pdf',
          },
          {
            index: 3,
            meta: {
              size: 12917556,
            },
            name: 'SignalPresentation copy 3.pdf',
            type: 'pdf',
            url: 'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246683/SignalPresentation+copy+3.pdf',
          },
        ],
        attachments_uploaded: true,
        audios: [],
        chatroom_id: 70716,
        community_id: 50421,
        created_at: '16:54',
        created_epoch: 1676373876197,
        date: '14 Feb 2023',
        has_files: true,
        id: 246683,
        images: [],
        is_edited: false,
        member: {
          id: 87040,
          image_url: '',
          is_guest: false,
          is_owner: false,
          member_since: 'Member since Jan 05 2023',
          member_since_epoch: 1672910682,
          name: 'USERONE',
          organisation_name: null,
          route:
            'route://member_community_profile?community_id=50421&member_id=87040',
          state: 4,
          updated_at: 1672910682,
          user_unique_id: '3cdcaf10-1950-4997-b48e-7a29bbe3dcdc',
        },
        pdf: [
          {
            index: 0,
            meta: {
              size: 12917556,
            },
            name: 'SignalPresentation.pdf',
            pdf_file:
              'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246683/SignalPresentation.pdf',
            type: 'pdf',
          },
          {
            index: 1,
            meta: {
              size: 12917556,
            },
            name: 'SignalPresentation copy.pdf',
            pdf_file:
              'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246683/SignalPresentation+copy.pdf',
            type: 'pdf',
          },
          {
            index: 2,
            meta: {
              size: 12917556,
            },
            name: 'SignalPresentation copy 2.pdf',
            pdf_file:
              'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246683/SignalPresentation+copy+2.pdf',
            type: 'pdf',
          },
          {
            index: 3,
            meta: {
              size: 12917556,
            },
            name: 'SignalPresentation copy 3.pdf',
            pdf_file:
              'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246683/SignalPresentation+copy+3.pdf',
            type: 'pdf',
          },
        ],
        reactions: [],
        state: 0,
        videos: [],
      },
      {
        answer: '',
        attachment_count: 4,
        attachments: [
          {
            index: 0,
            meta: {
              size: 12917556,
            },
            name: 'SignalPresentation.pdf',
            type: 'pdf',
            url: 'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246684/SignalPresentation.pdf',
          },
          {
            index: 1,
            meta: {
              size: 12917556,
            },
            name: 'SignalPresentation copy.pdf',
            type: 'pdf',
            url: 'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246684/SignalPresentation+copy.pdf',
          },
          {
            index: 2,
            meta: {
              size: 12917556,
            },
            name: 'SignalPresentation copy 2.pdf',
            type: 'pdf',
            url: 'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246684/SignalPresentation+copy+2.pdf',
          },
          {
            index: 3,
            meta: {
              size: 12917556,
            },
            name: 'SignalPresentation copy 3.pdf',
            type: 'pdf',
            url: 'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246684/SignalPresentation+copy+3.pdf',
          },
        ],
        attachments_uploaded: true,
        audios: [],
        chatroom_id: 70716,
        community_id: 50421,
        created_at: '16:55',
        created_epoch: 1676373900454,
        date: '14 Feb 2023',
        deleted_by: 87040,
        has_files: true,
        id: 246684,
        images: [],
        is_edited: false,
        member: {
          id: 87040,
          image_url: '',
          is_guest: false,
          is_owner: false,
          member_since: 'Member since Jan 05 2023',
          member_since_epoch: 1672910682,
          name: 'USERONE',
          organisation_name: null,
          route:
            'route://member_community_profile?community_id=50421&member_id=87040',
          state: 4,
          updated_at: 1672910682,
          user_unique_id: '3cdcaf10-1950-4997-b48e-7a29bbe3dcdc',
        },
        pdf: [
          {
            index: 0,
            meta: {
              size: 12917556,
            },
            name: 'SignalPresentation.pdf',
            pdf_file:
              'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246684/SignalPresentation.pdf',
            type: 'pdf',
          },
          {
            index: 1,
            meta: {
              size: 12917556,
            },
            name: 'SignalPresentation copy.pdf',
            pdf_file:
              'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246684/SignalPresentation+copy.pdf',
            type: 'pdf',
          },
          {
            index: 2,
            meta: {
              size: 12917556,
            },
            name: 'SignalPresentation copy 2.pdf',
            pdf_file:
              'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246684/SignalPresentation+copy+2.pdf',
            type: 'pdf',
          },
          {
            index: 3,
            meta: {
              size: 12917556,
            },
            name: 'SignalPresentation copy 3.pdf',
            pdf_file:
              'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246684/SignalPresentation+copy+3.pdf',
            type: 'pdf',
          },
        ],
        reactions: [],
        state: 0,
        videos: [],
      },
      {
        answer: 'multiple docs(pdf)',
        attachment_count: 0,
        attachments_uploaded: false,
        chatroom_id: 70716,
        community_id: 50421,
        created_at: '16:55',
        created_epoch: 1676373959253,
        date: '14 Feb 2023',
        has_files: false,
        id: 246685,
        is_edited: false,
        member: {
          id: 87040,
          image_url: '',
          is_guest: false,
          is_owner: false,
          member_since: 'Member since Jan 05 2023',
          member_since_epoch: 1672910682,
          name: 'USERONE',
          organisation_name: null,
          route:
            'route://member_community_profile?community_id=50421&member_id=87040',
          state: 4,
          updated_at: 1672910682,
          user_unique_id: '3cdcaf10-1950-4997-b48e-7a29bbe3dcdc',
        },
        reactions: [],
        reply_conversation: 246683,
        reply_conversation_object: {
          answer: '',
          attachment_count: 4,
          attachments: [
            {
              index: 0,
              meta: {
                size: 12917556,
              },
              name: 'SignalPresentation.pdf',
              type: 'pdf',
              url: 'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246683/SignalPresentation.pdf',
            },
            {
              index: 1,
              meta: {
                size: 12917556,
              },
              name: 'SignalPresentation copy.pdf',
              type: 'pdf',
              url: 'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246683/SignalPresentation+copy.pdf',
            },
            {
              index: 2,
              meta: {
                size: 12917556,
              },
              name: 'SignalPresentation copy 2.pdf',
              type: 'pdf',
              url: 'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246683/SignalPresentation+copy+2.pdf',
            },
            {
              index: 3,
              meta: {
                size: 12917556,
              },
              name: 'SignalPresentation copy 3.pdf',
              type: 'pdf',
              url: 'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246683/SignalPresentation+copy+3.pdf',
            },
          ],
          attachments_uploaded: true,
          audios: [],
          chatroom_id: 70716,
          community_id: 50421,
          created_at: 1676373876197,
          created_epoch: 1676373876197,
          date: '14 Feb 2023',
          has_files: true,
          id: 246683,
          images: [],
          is_edited: false,
          member: {
            id: 87040,
            image_url: '',
            is_guest: false,
            is_owner: false,
            member_since: 'Member since Jan 05 2023',
            member_since_epoch: 1672910682,
            name: 'USERONE',
            organisation_name: null,
            route:
              'route://member_community_profile?community_id=50421&member_id=87040',
            state: 4,
            updated_at: 1672910682,
            user_unique_id: '3cdcaf10-1950-4997-b48e-7a29bbe3dcdc',
          },
          pdf: [
            {
              index: 0,
              meta: {
                size: 12917556,
              },
              name: 'SignalPresentation.pdf',
              pdf_file:
                'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246683/SignalPresentation.pdf',
              type: 'pdf',
            },
            {
              index: 1,
              meta: {
                size: 12917556,
              },
              name: 'SignalPresentation copy.pdf',
              pdf_file:
                'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246683/SignalPresentation+copy.pdf',
              type: 'pdf',
            },
            {
              index: 2,
              meta: {
                size: 12917556,
              },
              name: 'SignalPresentation copy 2.pdf',
              pdf_file:
                'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246683/SignalPresentation+copy+2.pdf',
              type: 'pdf',
            },
            {
              index: 3,
              meta: {
                size: 12917556,
              },
              name: 'SignalPresentation copy 3.pdf',
              pdf_file:
                'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246683/SignalPresentation+copy+3.pdf',
              type: 'pdf',
            },
          ],
          reactions: [],
          state: 0,
          videos: [],
        },
        state: 0,
      },
      {
        answer: 'multiple docs(pdf)',
        attachment_count: 0,
        attachments_uploaded: false,
        chatroom_id: 70716,
        community_id: 50421,
        created_at: '16:55',
        created_epoch: 1676373959253,
        date: '14 Feb 2023',
        deleted_by: 87040,
        has_files: false,
        id: 246686,
        is_edited: false,
        member: {
          id: 87040,
          image_url: '',
          is_guest: false,
          is_owner: false,
          member_since: 'Member since Jan 05 2023',
          member_since_epoch: 1672910682,
          name: 'USERONE',
          organisation_name: null,
          route:
            'route://member_community_profile?community_id=50421&member_id=87040',
          state: 4,
          updated_at: 1672910682,
          user_unique_id: '3cdcaf10-1950-4997-b48e-7a29bbe3dcdc',
        },
        reactions: [],
        reply_conversation: 246683,
        reply_conversation_object: {
          answer: '',
          attachment_count: 4,
          attachments: [
            {
              index: 0,
              meta: {
                size: 12917556,
              },
              name: 'SignalPresentation.pdf',
              type: 'pdf',
              url: 'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246683/SignalPresentation.pdf',
            },
            {
              index: 1,
              meta: {
                size: 12917556,
              },
              name: 'SignalPresentation copy.pdf',
              type: 'pdf',
              url: 'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246683/SignalPresentation+copy.pdf',
            },
            {
              index: 2,
              meta: {
                size: 12917556,
              },
              name: 'SignalPresentation copy 2.pdf',
              type: 'pdf',
              url: 'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246683/SignalPresentation+copy+2.pdf',
            },
            {
              index: 3,
              meta: {
                size: 12917556,
              },
              name: 'SignalPresentation copy 3.pdf',
              type: 'pdf',
              url: 'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246683/SignalPresentation+copy+3.pdf',
            },
          ],
          attachments_uploaded: true,
          audios: [],
          chatroom_id: 70716,
          community_id: 50421,
          created_at: 1676373876197,
          created_epoch: 1676373876197,
          date: '14 Feb 2023',
          has_files: true,
          id: 246683,
          images: [],
          is_edited: false,
          member: {
            id: 87040,
            image_url: '',
            is_guest: false,
            is_owner: false,
            member_since: 'Member since Jan 05 2023',
            member_since_epoch: 1672910682,
            name: 'USERONE',
            organisation_name: null,
            route:
              'route://member_community_profile?community_id=50421&member_id=87040',
            state: 4,
            updated_at: 1672910682,
            user_unique_id: '3cdcaf10-1950-4997-b48e-7a29bbe3dcdc',
          },
          pdf: [
            {
              index: 0,
              meta: {
                size: 12917556,
              },
              name: 'SignalPresentation.pdf',
              pdf_file:
                'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246683/SignalPresentation.pdf',
              type: 'pdf',
            },
            {
              index: 1,
              meta: {
                size: 12917556,
              },
              name: 'SignalPresentation copy.pdf',
              pdf_file:
                'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246683/SignalPresentation+copy.pdf',
              type: 'pdf',
            },
            {
              index: 2,
              meta: {
                size: 12917556,
              },
              name: 'SignalPresentation copy 2.pdf',
              pdf_file:
                'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246683/SignalPresentation+copy+2.pdf',
              type: 'pdf',
            },
            {
              index: 3,
              meta: {
                size: 12917556,
              },
              name: 'SignalPresentation copy 3.pdf',
              pdf_file:
                'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246683/SignalPresentation+copy+3.pdf',
              type: 'pdf',
            },
          ],
          reactions: [],
          state: 0,
          videos: [],
        },
        state: 0,
      },
      {
        answer: 'single doc',
        attachment_count: 1,
        attachments: [
          {
            index: 0,
            meta: {
              size: 12917556,
            },
            name: 'SignalPresentation.pdf',
            type: 'pdf',
            url: 'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246687/SignalPresentation.pdf',
          },
        ],
        attachments_uploaded: true,
        audios: [],
        chatroom_id: 70716,
        community_id: 50421,
        created_at: '16:56',
        created_epoch: 1676374011781,
        date: '14 Feb 2023',
        has_files: true,
        id: 246687,
        images: [],
        is_edited: false,
        last_seen: true,
        member: {
          id: 87040,
          image_url: '',
          is_guest: false,
          is_owner: false,
          member_since: 'Member since Jan 05 2023',
          member_since_epoch: 1672910682,
          name: 'USERONE',
          organisation_name: null,
          route:
            'route://member_community_profile?community_id=50421&member_id=87040',
          state: 4,
          updated_at: 1672910682,
          user_unique_id: '3cdcaf10-1950-4997-b48e-7a29bbe3dcdc',
        },
        pdf: [
          {
            index: 0,
            meta: {
              size: 12917556,
            },
            name: 'SignalPresentation.pdf',
            pdf_file:
              'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246687/SignalPresentation.pdf',
            type: 'pdf',
          },
        ],
        reactions: [],
        state: 0,
        videos: [],
      },
      {
        answer: 'reply single doc',
        attachment_count: 0,
        attachments_uploaded: false,
        chatroom_id: 70716,
        community_id: 50421,
        created_at: '17:09',
        created_epoch: 1676374745088,
        date: '14 Feb 2023',
        has_files: false,
        id: 246698,
        is_edited: false,
        last_seen: true,
        member: {
          id: 87040,
          image_url: '',
          is_guest: false,
          is_owner: false,
          member_since: 'Member since Jan 05 2023',
          member_since_epoch: 1672910682,
          name: 'USERONE',
          organisation_name: null,
          route:
            'route://member_community_profile?community_id=50421&member_id=87040',
          state: 4,
          updated_at: 1672910682,
          user_unique_id: '3cdcaf10-1950-4997-b48e-7a29bbe3dcdc',
        },
        reactions: [],
        reply_conversation: 246687,
        reply_conversation_object: {
          answer: 'single doc',
          attachment_count: 1,
          attachments: [
            {
              index: 0,
              meta: {
                size: 12917556,
              },
              name: 'SignalPresentation.pdf',
              type: 'pdf',
              url: 'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246687/SignalPresentation.pdf',
            },
          ],
          attachments_uploaded: true,
          audios: [],
          chatroom_id: 70716,
          community_id: 50421,
          created_at: 1676374011781,
          created_epoch: 1676374011781,
          date: '14 Feb 2023',
          has_files: true,
          id: 246687,
          images: [],
          is_edited: false,
          member: {
            id: 87040,
            image_url: '',
            is_guest: false,
            is_owner: false,
            member_since: 'Member since Jan 05 2023',
            member_since_epoch: 1672910682,
            name: 'USERONE',
            organisation_name: null,
            route:
              'route://member_community_profile?community_id=50421&member_id=87040',
            state: 4,
            updated_at: 1672910682,
            user_unique_id: '3cdcaf10-1950-4997-b48e-7a29bbe3dcdc',
          },
          pdf: [
            {
              index: 0,
              meta: {
                size: 12917556,
              },
              name: 'SignalPresentation.pdf',
              pdf_file:
                'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246687/SignalPresentation.pdf',
              type: 'pdf',
            },
          ],
          reactions: [],
          state: 0,
          videos: [],
        },
        state: 0,
      },
      {
        answer: '',
        attachment_count: 2,
        attachments: [
          {
            index: 0,
            meta: {
              size: 1912,
            },
            name: 'open_files3x.png',
            type: 'image',
            url: 'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246762/open_files3x.png',
          },
          {
            index: 1,
            meta: {
              size: 1405,
            },
            name: 'participants_icon3x.png',
            type: 'image',
            url: 'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246762/participants_icon3x.png',
          },
        ],
        attachments_uploaded: true,
        audios: [],
        chatroom_id: 70716,
        community_id: 50421,
        created_at: '00:24',
        created_epoch: 1676400849106,
        date: '15 Feb 2023',
        has_files: true,
        id: 246762,
        images: [
          {
            image_url:
              'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246762/open_files3x.png',
            index: 0,
            meta: {
              size: 1912,
            },
            name: 'open_files3x.png',
            type: 'image',
          },
          {
            image_url:
              'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246762/participants_icon3x.png',
            index: 1,
            meta: {
              size: 1405,
            },
            name: 'participants_icon3x.png',
            type: 'image',
          },
        ],
        is_edited: false,
        last_seen: true,
        member: {
          id: 87040,
          image_url: '',
          is_guest: false,
          is_owner: false,
          member_since: 'Member since Jan 05 2023',
          member_since_epoch: 1672910682,
          name: 'USERONE',
          organisation_name: null,
          route:
            'route://member_community_profile?community_id=50421&member_id=87040',
          state: 4,
          updated_at: 1672910682,
          user_unique_id: '3cdcaf10-1950-4997-b48e-7a29bbe3dcdc',
        },
        pdf: [],
        reactions: [],
        state: 0,
        videos: [],
      },
      {
        answer: '',
        attachment_count: 3,
        attachments: [
          {
            index: 0,
            meta: {
              size: 490,
            },
            name: 'cross_icon3x.png',
            type: 'image',
            url: 'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246763/cross_icon3x.png',
          },
          {
            index: 1,
            meta: {
              size: 430,
            },
            name: 'document_icon3x.png',
            type: 'image',
            url: 'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246763/document_icon3x.png',
          },
          {
            index: 2,
            meta: {
              size: 521,
            },
            name: 'down_arrow3x.png',
            type: 'image',
            url: 'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246763/down_arrow3x.png',
          },
        ],
        attachments_uploaded: true,
        audios: [],
        chatroom_id: 70716,
        community_id: 50421,
        created_at: '00:25',
        created_epoch: 1676400918141,
        date: '15 Feb 2023',
        has_files: true,
        id: 246763,
        images: [
          {
            image_url:
              'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246763/cross_icon3x.png',
            index: 0,
            meta: {
              size: 490,
            },
            name: 'cross_icon3x.png',
            type: 'image',
          },
          {
            image_url:
              'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246763/document_icon3x.png',
            index: 1,
            meta: {
              size: 430,
            },
            name: 'document_icon3x.png',
            type: 'image',
          },
          {
            image_url:
              'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/70716/conversation/246763/down_arrow3x.png',
            index: 2,
            meta: {
              size: 521,
            },
            name: 'down_arrow3x.png',
            type: 'image',
          },
        ],
        is_edited: false,
        last_seen: true,
        member: {
          id: 87040,
          image_url: '',
          is_guest: false,
          is_owner: false,
          member_since: 'Member since Jan 05 2023',
          member_since_epoch: 1672910682,
          name: 'USERONE',
          organisation_name: null,
          route:
            'route://member_community_profile?community_id=50421&member_id=87040',
          state: 4,
          updated_at: 1672910682,
          user_unique_id: '3cdcaf10-1950-4997-b48e-7a29bbe3dcdc',
        },
        pdf: [],
        reactions: [],
        state: 0,
        videos: [],
      },
    ],
  },
};
