export const dummyData = {
  success: true,
  data: {
    my_chatrooms: [
      {
        chatroom: {
          access: null,
          answer_text: '',
          answers_count: 0,
          attachment_count: 0,
          attachments: [],
          attachments_uploaded: false,
          attending_count: 0,
          attending_status: false,
          audio_count: 0,
          audios: [],
          auto_follow_done: true,
          card_creation_time: '07:51 PM',
          chatroom_image_url:
            'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/profile/1669284820565',
          community_id: 50421,
          community_name: 'Notification settings',
          created_at: '19:51',
          date: '20 Oct 2022',
          date_epoch: 1666275716,
          date_time: 0,
          duration: 0,
          follow_status: true,
          has_event_recording: false,
          header: 'NC2',
          id: 28540,
          image_count: 0,
          images: [],
          include_members_later: true,
          is_edited: true,
          is_guest: false,
          is_paid: false,
          is_pending: false,
          is_private: false,
          is_private_member: false,
          is_secret: false,
          is_tagged: false,
          member: {
            custom_intro_text: 'Created this community on 17 Aug 2022',
            custom_title: 'Owner',
            id: 3547,
            image_url: '',
            is_guest: false,
            is_owner: true,
            member_since: 'Member since Aug 17 2022',
            member_since_epoch: 1660729281,
            name: 'Notification settings bot',
            organisation_name: null,
            route:
              'route://member_community_profile?community_id=50421&member_id=3547',
            state: 1,
            updated_at: 1672224763,
            user_unique_id: '53f5f457-70e3-4f07-9fb9-078b12f36510',
          },
          mute_status: false,
          online_link_enable_before: 900000,
          online_link_type: null,
          pdf: [],
          pdf_count: 0,
          polls_count: 0,
          reactions: [
            {
              member: {
                id: 3734,
                image_url: '',
                name: 'Push user',
              },
              reaction: '😂',
              updated_at: 1667200975568,
            },
          ],
          secret_chatroom_left: false,
          share_link: '',
          state: 1,
          title: 'NC2', // title
          type: 0,
          video_count: 0,
          videos: [],
        },
        community: {
          auto_approval: true,
          branding: {
            advanced: {
              buttons_icons_colour: '',
              header_colour: '',
              text_links_colour: '',
            },
            basic: {
              primary_colour: '#007AFF',
            },
          },
          community_setting_rights: [
            {
              id: 1,
              is_locked: false,
              is_selected: true,
              state: 0,
              title: 'Create chat rooms',
            },
            {
              id: 2,
              is_locked: false,
              is_selected: true,
              state: 1,
              title: 'Create polls',
            },
            {
              id: 3,
              is_locked: false,
              is_selected: true,
              state: 2,
              title: 'Create events',
            },
            {
              id: 4,
              is_locked: false,
              is_selected: true,
              state: 3,
              title: 'Respond in chat rooms',
            },
            {
              id: 6,
              is_locked: false,
              is_selected: true,
              state: 5,
              sub_title:
                "If auto-approved, member's chat rooms will be posted instantly and would not need any approval.",
              title: 'Auto-approve created chat rooms',
            },
            {
              id: 7,
              is_locked: false,
              is_selected: true,
              state: 6,
              title: 'Create secret chat rooms',
            },
            {
              id: 8,
              is_locked: false,
              is_selected: false,
              state: 7,
              sub_title:
                'Direct messaging can happen only between a community manager and a community member (not among 2 members).',
              title: 'Direct messages',
            },
          ],
          fee_event: 5,
          fee_membership: 5,
          fee_payment_pages: 5,
          grace_period: 0,
          hide_dm_tab: false,
          id: 50421,
          image_url:
            'https://beta.likeminds.community/media/media/community/default.jpeg',
          is_discoverable: false,
          is_freemium_community: false,
          is_paid: false,
          is_whitelabel: false,
          members_count: 49,
          name: 'Notification settings',
          purpose: 'We will send all the announcements here on this chatroom.',
          referral_enabled: false,
          sub_type: 1111,
          type: 1111,
          updated_at: 1672224763,
          whitelabel_info: null,
        },
        conversation_users: [
          {
            id: 87162,
            image_url: '',
            name: 'Sanjay SDK 1',
          },
          {
            id: 86973,
            image_url: '',
            name: 'yet',
          },
        ],
        is_draft: false,
        last_conversation: {
          answer: 'k',  // last message
          attachment_count: 0,
          attachments_uploaded: false,
          chatroom_id: 28540,
          community_id: 50421,
          created_at: 1674551685425,
          created_epoch: 1674551685425,
          date: '24 Jan 2023',
          has_files: false,
          id: 242133,
          is_edited: false,
          member: {
            id: 87162,
            image_url: '',
            is_guest: false,
            is_owner: false,
            member_since: 'Member since Jan 18 2023',
            member_since_epoch: 1674026517,
            name: 'Sanjay SDK 1', // last message member name
            organisation_name: null,
            route:
              'route://member_community_profile?community_id=50421&member_id=87162',
            state: 4,
            updated_at: 1674026517,
            user_unique_id: '18776a33-0581-453f-8e76-38938c917bf9',
          },
          reactions: [],
          reply_conversation: 241728,
          reply_conversation_object: {
            answer: 'h',
            attachment_count: 0,
            attachments_uploaded: false,
            chatroom_id: 28540,
            community_id: 50421,
            created_at: 1674399663468, 
            created_epoch: 1674399663468, // time
            date: '22 Jan 2023',
            has_files: false,
            id: 241728,
            is_edited: false,
            member: {
              id: 86973,
              image_url: '',
              is_guest: false,
              is_owner: false,
              member_since: 'Member since Dec 28 2022',
              member_since_epoch: 1672211747,
              name: 'yet',
              organisation_name: null,
              route:
                'route://member_community_profile?community_id=50421&member_id=86973',
              state: 4,
              updated_at: 1672217446,
              user_unique_id: 'c5ec1895-55ce-400c-bba7-889b53010f19',
            },
            reactions: [],
            state: 0,
          },
          state: 0,
        },
        last_conversation_time: '24/01/23',
        member_right_states: [5, 3, 2, 1, 0],
        member_state: 4,
        second_last_conversation: {
          answer: 'm',
          attachment_count: 0,
          attachments_uploaded: false,
          chatroom_id: 28540,
          community_id: 50421,
          created_at: 1674399675270,
          created_epoch: 1674399675270,
          date: '22 Jan 2023',
          has_files: false,
          id: 241730,
          is_edited: false,
          member: {
            id: 86973,
            image_url: '',
            is_guest: false,
            is_owner: false,
            member_since: 'Member since Dec 28 2022',
            member_since_epoch: 1672211747,
            name: 'yet',
            organisation_name: null,
            route:
              'route://member_community_profile?community_id=50421&member_id=86973',
            state: 4,
            updated_at: 1672217446,
            user_unique_id: 'c5ec1895-55ce-400c-bba7-889b53010f19',
          },
          reactions: [],
          state: 0,
        },
        unseen_conversation_count: 0, // msg count
      },
      {
        chatroom: {
          access: null,
          answer_text: '',
          answers_count: 0,
          attachment_count: 0,
          attachments: [],
          attachments_uploaded: false,
          attending_count: 0,
          attending_status: false,
          audio_count: 0,
          audios: [],
          auto_follow_done: true,
          card_creation_time: '03:11 PM',
          community_id: 50421,
          community_name: 'Notification settings',
          chatroom_image_url:
          'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/profile/1669284820565',
          created_at: '15:11',
          date: '17 Aug 2022',
          date_epoch: 1660729283,
          date_time: 0,
          duration: 0,
          follow_status: true,
          has_event_recording: false,
          header: 'General Chat Room',
          id: 27846,
          image_count: 0,
          images: [],
          include_members_later: true,
          is_edited: false,
          is_guest: false,
          is_paid: false,
          is_pending: false,
          is_private: false,
          is_private_member: false,
          is_secret: false,
          is_tagged: false,
          member: {
            custom_intro_text: 'Created this community on 17 Aug 2022',
            custom_title: 'Owner',
            id: 3547,
            image_url: '',
            is_guest: false,
            is_owner: true,
            member_since: 'Member since Aug 17 2022',
            member_since_epoch: 1660729281,
            name: 'Notification settings bot',
            organisation_name: null,
            route:
              'route://member_community_profile?community_id=50421&member_id=3547',
            state: 1,
            updated_at: 1672224763,
            user_unique_id: '53f5f457-70e3-4f07-9fb9-078b12f36510',
          },
          mute_status: false,
          online_link_enable_before: 900000,
          online_link_type: null,
          pdf: [],
          pdf_count: 0,
          polls_count: 0,
          reactions: [],
          secret_chatroom_left: false,
          share_link: '',
          state: 1,
          title:
            'This chatroom is to have off-topic conversations with the community members.',
          type: 0,
          video_count: 0,
          videos: [],
        },
        community: {
          auto_approval: true,
          branding: {
            advanced: {
              buttons_icons_colour: '',
              header_colour: '',
              text_links_colour: '',
            },
            basic: {
              primary_colour: '#007AFF',
            },
          },
          community_setting_rights: [
            {
              id: 1,
              is_locked: false,
              is_selected: true,
              state: 0,
              title: 'Create chat rooms',
            },
            {
              id: 2,
              is_locked: false,
              is_selected: true,
              state: 1,
              title: 'Create polls',
            },
            {
              id: 3,
              is_locked: false,
              is_selected: true,
              state: 2,
              title: 'Create events',
            },
            {
              id: 4,
              is_locked: false,
              is_selected: true,
              state: 3,
              title: 'Respond in chat rooms',
            },
            {
              id: 6,
              is_locked: false,
              is_selected: true,
              state: 5,
              sub_title:
                "If auto-approved, member's chat rooms will be posted instantly and would not need any approval.",
              title: 'Auto-approve created chat rooms',
            },
            {
              id: 7,
              is_locked: false,
              is_selected: true,
              state: 6,
              title: 'Create secret chat rooms',
            },
            {
              id: 8,
              is_locked: false,
              is_selected: false,
              state: 7,
              sub_title:
                'Direct messaging can happen only between a community manager and a community member (not among 2 members).',
              title: 'Direct messages',
            },
          ],
          fee_event: 5,
          fee_membership: 5,
          fee_payment_pages: 5,
          grace_period: 0,
          hide_dm_tab: false,
          id: 50421,
          image_url:
            'https://beta.likeminds.community/media/media/community/default.jpeg',
          is_discoverable: false,
          is_freemium_community: false,
          is_paid: false,
          is_whitelabel: false,
          members_count: 49,
          name: 'Notification settings',
          purpose: 'We will send all the announcements here on this chatroom.',
          referral_enabled: false,
          sub_type: 1111,
          type: 1111,
          updated_at: 1672224763,
          whitelabel_info: null,
        },
        conversation_users: [
          {
            id: 87214,
            image_url: '',
            name: 'Test',
          },
          {
            id: 86986,
            image_url: '',
            name: 'Ankit',
          },
        ],
        is_draft: false,
        last_conversation: {
          answer: 'The new gf',
          attachment_count: 1,
          attachments: [
            {
              height: 3024,
              index: 0,
              meta: {
                size: 3523197,
              },
              name: '9793C4A4-7110-4510-963A-EA1478091A75-45693-000073F49B8B1E4D.png',
              type: 'image',
              url: 'https://s3.ap-south-1.amazonaws.com/beta-likeminds-media/files/collabcard/27846/conversation/241961/17ED9218-A810-4FF6-A15E-8F83BEC21025-45693-000073F53EB6676E.jpeg',
              width: 4032,
            },
          ],
          attachments_uploaded: true,
          audios: [],
          chatroom_id: 27846,
          community_id: 50421,
          created_at: 1674468196227,
          created_epoch: 1674468196227,
          date: '23 Jan 2023',
          has_files: true,
          id: 241961,
          images: [
            {
              height: 3024,
              image_url:
                'https://s3.ap-south-1.amazonaws.com/beta-likeminds-media/files/collabcard/27846/conversation/241961/17ED9218-A810-4FF6-A15E-8F83BEC21025-45693-000073F53EB6676E.jpeg',
              index: 0,
              meta: {
                size: 3523197,
              },
              name: '9793C4A4-7110-4510-963A-EA1478091A75-45693-000073F49B8B1E4D.png',
              type: 'image',
              width: 4032,
            },
          ],
          is_edited: false,
          member: {
            id: 87214,
            image_url: '',
            is_guest: false,
            is_owner: false,
            member_since: 'Member since Jan 20 2023',
            member_since_epoch: 1674196605,
            name: 'Test',
            organisation_name: null,
            route:
              'route://member_community_profile?community_id=50421&member_id=87214',
            state: 4,
            updated_at: 1674468068,
            user_unique_id: 'dd2d2a0f-44da-42e5-81f3-6cd0cf3e899a',
          },
          pdf: [],
          reactions: [],
          state: 0,
          temporary_id: '7A211B5E-1C9A-4AE8-AD12-298ECB382956',
          videos: [],
        },
        last_conversation_time: '23/01/23',
        member_right_states: [5, 3, 2, 1, 0],
        member_state: 4,
        second_last_conversation: {
          answer: 'Fdjlh',
          attachment_count: 1,
          attachments: [
            {
              index: 0,
              meta: {
                duration: 38,
                size: 82656,
              },
              name: 'IMG_0012.MOV',
              thumbnail_url:
                'https://s3.ap-south-1.amazonaws.com/beta-likeminds-media/files/collabcard/27846/conversation/241960/94AC0A8B-AA1C-4608-B3DD-E4989AB8EA7C-45693-000073E123772A8A.jpeg',
              type: 'video',
              url: 'https://s3.ap-south-1.amazonaws.com/beta-likeminds-media/files/collabcard/27846/conversation/241960/04B848E6-6D70-431C-8AF9-01EB8BEFC699-45693-000073E141013825.MOV',
            },
          ],
          attachments_uploaded: true,
          audios: [],
          chatroom_id: 27846,
          community_id: 50421,
          created_at: 1674468111330,
          created_epoch: 1674468111330,
          date: '23 Jan 2023',
          has_files: true,
          id: 241960,
          images: [],
          is_edited: false,
          member: {
            id: 87214,
            image_url: '',
            is_guest: false,
            is_owner: false,
            member_since: 'Member since Jan 20 2023',
            member_since_epoch: 1674196605,
            name: 'Test',
            organisation_name: null,
            route:
              'route://member_community_profile?community_id=50421&member_id=87214',
            state: 4,
            updated_at: 1674468068,
            user_unique_id: 'dd2d2a0f-44da-42e5-81f3-6cd0cf3e899a',
          },
          pdf: [],
          reactions: [],
          state: 0,
          temporary_id: '1AE25C66-60E7-42B5-807A-81E5D9AAE9E6',
          videos: [
            {
              index: 0,
              meta: {
                duration: 38,
                size: 82656,
              },
              name: 'IMG_0012.MOV',
              thumbnail_url:
                'https://s3.ap-south-1.amazonaws.com/beta-likeminds-media/files/collabcard/27846/conversation/241960/94AC0A8B-AA1C-4608-B3DD-E4989AB8EA7C-45693-000073E123772A8A.jpeg',
              type: 'video',
              video_url:
                'https://s3.ap-south-1.amazonaws.com/beta-likeminds-media/files/collabcard/27846/conversation/241960/04B848E6-6D70-431C-8AF9-01EB8BEFC699-45693-000073E141013825.MOV',
            },
          ],
        },
        unseen_conversation_count: 0,
      },
      {
        chatroom: {
          access: null,
          answer_text: '',
          answers_count: 0,
          attachment_count: 0,
          attachments: [],
          attachments_uploaded: false,
          attending_count: 0,
          attending_status: false,
          audio_count: 0,
          audios: [],
          auto_follow_done: true,
          card_creation_time: '07:24 PM',
          chatroom_image_url:
            'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/chatroom/image/1661262839202',
          community_id: 50421,
          community_name: 'Notification settings',
          created_at: '19:24',
          date: '23 Aug 2022',
          date_epoch: 1661262843,
          date_time: 0,
          duration: 0,
          follow_status: true,
          has_event_recording: false,
          header: 'Testing 2',
          id: 27908,
          image_count: 0,
          images: [],
          include_members_later: true,
          is_edited: false,
          is_guest: false,
          is_paid: false,
          is_pending: false,
          is_private: false,
          is_private_member: false,
          is_secret: false,
          is_tagged: false,
          member: {
            custom_intro_text: 'Created this community on 17 Aug 2022',
            custom_title: 'Owner',
            id: 3547,
            image_url: '',
            is_guest: false,
            is_owner: true,
            member_since: 'Member since Aug 17 2022',
            member_since_epoch: 1660729281,
            name: 'Notification settings bot',
            organisation_name: null,
            route:
              'route://member_community_profile?community_id=50421&member_id=3547',
            state: 1,
            updated_at: 1672224763,
            user_unique_id: '53f5f457-70e3-4f07-9fb9-078b12f36510',
          },
          mute_status: false,
          online_link_enable_before: 900000,
          online_link_type: null,
          pdf: [],
          pdf_count: 0,
          polls_count: 0,
          reactions: [],
          secret_chatroom_left: false,
          share_link: '',
          state: 1,
          title: 'Testing 2',
          type: 0,
          video_count: 0,
          videos: [],
        },
        community: {
          auto_approval: true,
          branding: {
            advanced: {
              buttons_icons_colour: '',
              header_colour: '',
              text_links_colour: '',
            },
            basic: {
              primary_colour: '#007AFF',
            },
          },
          community_setting_rights: [
            {
              id: 1,
              is_locked: false,
              is_selected: true,
              state: 0,
              title: 'Create chat rooms',
            },
            {
              id: 2,
              is_locked: false,
              is_selected: true,
              state: 1,
              title: 'Create polls',
            },
            {
              id: 3,
              is_locked: false,
              is_selected: true,
              state: 2,
              title: 'Create events',
            },
            {
              id: 4,
              is_locked: false,
              is_selected: true,
              state: 3,
              title: 'Respond in chat rooms',
            },
            {
              id: 6,
              is_locked: false,
              is_selected: true,
              state: 5,
              sub_title:
                "If auto-approved, member's chat rooms will be posted instantly and would not need any approval.",
              title: 'Auto-approve created chat rooms',
            },
            {
              id: 7,
              is_locked: false,
              is_selected: true,
              state: 6,
              title: 'Create secret chat rooms',
            },
            {
              id: 8,
              is_locked: false,
              is_selected: false,
              state: 7,
              sub_title:
                'Direct messaging can happen only between a community manager and a community member (not among 2 members).',
              title: 'Direct messages',
            },
          ],
          fee_event: 5,
          fee_membership: 5,
          fee_payment_pages: 5,
          grace_period: 0,
          hide_dm_tab: false,
          id: 50421,
          image_url:
            'https://beta.likeminds.community/media/media/community/default.jpeg',
          is_discoverable: false,
          is_freemium_community: false,
          is_paid: false,
          is_whitelabel: false,
          members_count: 49,
          name: 'Notification settings',
          purpose: 'We will send all the announcements here on this chatroom.',
          referral_enabled: false,
          sub_type: 1111,
          type: 1111,
          updated_at: 1672224763,
          whitelabel_info: null,
        },
        conversation_users: [
          {
            id: 3895,
            image_url: '',
            name: 'sanjay',
          },
          {
            id: 86973,
            image_url: '',
            name: 'yet',
          },
        ],
        is_draft: false,
        last_conversation: {
          answer: 'Yeyeye',
          attachment_count: 0,
          attachments_uploaded: false,
          chatroom_id: 27908,
          community_id: 50421,
          created_at: 1674215776099,
          created_epoch: 1674215776099,
          date: '20 Jan 2023',
          has_files: false,
          id: 241634,
          is_edited: false,
          member: {
            id: 3895,
            image_url: '',
            is_guest: false,
            is_owner: false,
            member_since: 'Member since Dec 07 2022',
            member_since_epoch: 1670395292,
            name: 'sanjay',
            organisation_name: null,
            route:
              'route://member_community_profile?community_id=50421&member_id=3895',
            state: 4,
            updated_at: 1674790732,
            user_unique_id: '78cb8da7-bade-4d34-afb8-91c8e151e212',
          },
          reactions: [],
          state: 0,
          temporary_id: '3B4A6D0C-84B0-4EE7-B011-6AE1D4BEF2CE',
        },
        last_conversation_time: '20/01/23',
        member_right_states: [5, 3, 2, 1, 0],
        member_state: 4,
        second_last_conversation: {
          answer: 'Test',
          attachment_count: 0,
          attachments_uploaded: false,
          chatroom_id: 27908,
          community_id: 50421,
          created_at: 1674215761742,
          created_epoch: 1674215761742,
          date: '20 Jan 2023',
          has_files: false,
          id: 241633,
          is_edited: false,
          member: {
            id: 3895,
            image_url: '',
            is_guest: false,
            is_owner: false,
            member_since: 'Member since Dec 07 2022',
            member_since_epoch: 1670395292,
            name: 'sanjay',
            organisation_name: null,
            route:
              'route://member_community_profile?community_id=50421&member_id=3895',
            state: 4,
            updated_at: 1674790732,
            user_unique_id: '78cb8da7-bade-4d34-afb8-91c8e151e212',
          },
          reactions: [],
          state: 0,
          temporary_id: '0EE8AE31-44D6-440B-BAB6-811A2D8BDC2A',
        },
        unseen_conversation_count: 0,
      },
      {
        chatroom: {
          access: null,
          answer_text: '',
          answers_count: 0,
          attachment_count: 0,
          attachments: [],
          attachments_uploaded: false,
          attending_count: 0,
          attending_status: false,
          audio_count: 0,
          audios: [],
          auto_follow_done: true,
          card_creation_time: '07:19 PM',
          chatroom_image_url:
            'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/chatroom/image/1671889773717',
          community_id: 50421,
          community_name: 'Notification settings',
          created_at: '19:19',
          date: '24 Dec 2022',
          date_epoch: 1671889777,
          date_time: 0,
          duration: 0,
          follow_status: true,
          has_event_recording: false,
          header: 'Testing chatroom 2233',
          id: 69285,
          image_count: 0,
          images: [],
          include_members_later: true,
          is_edited: false,
          is_guest: false,
          is_paid: false,
          is_pending: false,
          is_private: false,
          is_private_member: false,
          is_secret: false,
          is_tagged: false,
          member: {
            custom_intro_text: 'Created this community on 17 Aug 2022',
            custom_title: 'Owner',
            id: 3547,
            image_url: '',
            is_guest: false,
            is_owner: true,
            member_since: 'Member since Aug 17 2022',
            member_since_epoch: 1660729281,
            name: 'Notification settings bot',
            organisation_name: null,
            route:
              'route://member_community_profile?community_id=50421&member_id=3547',
            state: 1,
            updated_at: 1672224763,
            user_unique_id: '53f5f457-70e3-4f07-9fb9-078b12f36510',
          },
          mute_status: false,
          online_link_enable_before: 900000,
          online_link_type: null,
          pdf: [],
          pdf_count: 0,
          polls_count: 0,
          reactions: [],
          secret_chatroom_left: false,
          share_link: '',
          state: 1,
          title: 'NNS',
          type: 0,
          video_count: 0,
          videos: [],
        },
        community: {
          auto_approval: true,
          branding: {
            advanced: {
              buttons_icons_colour: '',
              header_colour: '',
              text_links_colour: '',
            },
            basic: {
              primary_colour: '#007AFF',
            },
          },
          community_setting_rights: [
            {
              id: 1,
              is_locked: false,
              is_selected: true,
              state: 0,
              title: 'Create chat rooms',
            },
            {
              id: 2,
              is_locked: false,
              is_selected: true,
              state: 1,
              title: 'Create polls',
            },
            {
              id: 3,
              is_locked: false,
              is_selected: true,
              state: 2,
              title: 'Create events',
            },
            {
              id: 4,
              is_locked: false,
              is_selected: true,
              state: 3,
              title: 'Respond in chat rooms',
            },
            {
              id: 6,
              is_locked: false,
              is_selected: true,
              state: 5,
              sub_title:
                "If auto-approved, member's chat rooms will be posted instantly and would not need any approval.",
              title: 'Auto-approve created chat rooms',
            },
            {
              id: 7,
              is_locked: false,
              is_selected: true,
              state: 6,
              title: 'Create secret chat rooms',
            },
            {
              id: 8,
              is_locked: false,
              is_selected: false,
              state: 7,
              sub_title:
                'Direct messaging can happen only between a community manager and a community member (not among 2 members).',
              title: 'Direct messages',
            },
          ],
          fee_event: 5,
          fee_membership: 5,
          fee_payment_pages: 5,
          grace_period: 0,
          hide_dm_tab: false,
          id: 50421,
          image_url:
            'https://beta.likeminds.community/media/media/community/default.jpeg',
          is_discoverable: false,
          is_freemium_community: false,
          is_paid: false,
          is_whitelabel: false,
          members_count: 49,
          name: 'Notification settings',
          purpose: 'We will send all the announcements here on this chatroom.',
          referral_enabled: false,
          sub_type: 1111,
          type: 1111,
          updated_at: 1672224763,
          whitelabel_info: null,
        },
        conversation_users: [],
        is_draft: false,
        last_conversation_time: '24/12/22',
        member_right_states: [5, 3, 2, 1, 0],
        member_state: 4,
        unseen_conversation_count: 0,
      },
      {
        chatroom: {
          access: null,
          answer_text: '',
          answers_count: 0,
          attachment_count: 0,
          attachments: [],
          attachments_uploaded: false,
          attending_count: 0,
          attending_status: false,
          audio_count: 0,
          audios: [],
          auto_follow_done: false,
          card_creation_time: '03:11 PM',
          community_id: 50421,
          community_name: 'Notification settings',
          chatroom_image_url:
          'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/chatroom/image/1671889773717',
          created_at: '15:11',
          date: '17 Aug 2022',
          date_epoch: 1660729282,
          date_time: 0,
          duration: 0,
          follow_status: true,
          has_event_recording: false,
          header: 'Announcement Room 📣',
          id: 27845,
          image_count: 0,
          images: [],
          include_members_later: true,
          is_edited: false,
          is_guest: false,
          is_paid: false,
          is_pending: false,
          is_private: false,
          is_private_member: false,
          is_secret: false,
          is_tagged: false,
          member: {
            custom_intro_text: 'Created this community on 17 Aug 2022',
            custom_title: 'Owner',
            id: 3547,
            image_url: '',
            is_guest: false,
            is_owner: true,
            member_since: 'Member since Aug 17 2022',
            member_since_epoch: 1660729281,
            name: 'Notification settings bot',
            organisation_name: null,
            route:
              'route://member_community_profile?community_id=50421&member_id=3547',
            state: 1,
            updated_at: 1672224763,
            user_unique_id: '53f5f457-70e3-4f07-9fb9-078b12f36510',
          },
          mute_status: false,
          online_link_enable_before: 900000,
          online_link_type: null,
          pdf: [],
          pdf_count: 0,
          polls_count: 0,
          reactions: [],
          secret_chatroom_left: false,
          share_link: '',
          state: 1,
          title: 'We will send all the announcements here on this chatroom.',
          type: 7,
          video_count: 0,
          videos: [],
        },
        community: {
          auto_approval: true,
          branding: {
            advanced: {
              buttons_icons_colour: '',
              header_colour: '',
              text_links_colour: '',
            },
            basic: {
              primary_colour: '#007AFF',
            },
          },
          community_setting_rights: [
            {
              id: 1,
              is_locked: false,
              is_selected: true,
              state: 0,
              title: 'Create chat rooms',
            },
            {
              id: 2,
              is_locked: false,
              is_selected: true,
              state: 1,
              title: 'Create polls',
            },
            {
              id: 3,
              is_locked: false,
              is_selected: true,
              state: 2,
              title: 'Create events',
            },
            {
              id: 4,
              is_locked: false,
              is_selected: true,
              state: 3,
              title: 'Respond in chat rooms',
            },
            {
              id: 6,
              is_locked: false,
              is_selected: true,
              state: 5,
              sub_title:
                "If auto-approved, member's chat rooms will be posted instantly and would not need any approval.",
              title: 'Auto-approve created chat rooms',
            },
            {
              id: 7,
              is_locked: false,
              is_selected: true,
              state: 6,
              title: 'Create secret chat rooms',
            },
            {
              id: 8,
              is_locked: false,
              is_selected: false,
              state: 7,
              sub_title:
                'Direct messaging can happen only between a community manager and a community member (not among 2 members).',
              title: 'Direct messages',
            },
          ],
          fee_event: 5,
          fee_membership: 5,
          fee_payment_pages: 5,
          grace_period: 0,
          hide_dm_tab: false,
          id: 50421,
          image_url:
            'https://beta.likeminds.community/media/media/community/default.jpeg',
          is_discoverable: false,
          is_freemium_community: false,
          is_paid: false,
          is_whitelabel: false,
          members_count: 49,
          name: 'Notification settings',
          purpose: 'We will send all the announcements here on this chatroom.',
          referral_enabled: false,
          sub_type: 1111,
          type: 1111,
          updated_at: 1672224763,
          whitelabel_info: null,
        },
        conversation_users: [
          {
            id: 3563,
            image_url: '',
            name: 'Ankit Garg SDK',
          },
        ],
        is_draft: false,
        last_conversation: {
          answer: '<<push Singh|route://member/3731>>',
          attachment_count: 0,
          attachments_uploaded: false,
          chatroom_id: 27845,
          community_id: 50421,
          created_at: 1667279793382,
          created_epoch: 1667279793382,
          date: '01 Nov 2022',
          has_files: false,
          id: 143351,
          is_edited: false,
          member: {
            custom_intro_text: 'Created this community on 23 Aug 2022',
            custom_title: 'Community Manager',
            id: 3563,
            image_url: '',
            is_guest: false,
            is_owner: false,
            member_since: 'Member since Aug 23 2022',
            member_since_epoch: 1661262431,
            name: 'Ankit Garg SDK',
            organisation_name: null,
            route:
              'route://member_community_profile?community_id=50421&member_id=3563',
            state: 1,
            updated_at: 1668687647,
            user_unique_id: '53208f29-5d15-473e-ab70-5fd77605be0f',
          },
          reactions: [],
          state: 0,
          temporary_id: '-973779387',
        },
        last_conversation_time: '01/11/22',
        member_right_states: [5, 3, 2, 1, 0],
        member_state: 4,
        second_last_conversation: {
          answer: 'Hello',
          attachment_count: 0,
          attachments_uploaded: false,
          chatroom_id: 27845,
          community_id: 50421,
          created_at: 1667279787754,
          created_epoch: 1667279787754,
          date: '01 Nov 2022',
          has_files: false,
          id: 143350,
          is_edited: false,
          member: {
            custom_intro_text: 'Created this community on 23 Aug 2022',
            custom_title: 'Community Manager',
            id: 3563,
            image_url: '',
            is_guest: false,
            is_owner: false,
            member_since: 'Member since Aug 23 2022',
            member_since_epoch: 1661262431,
            name: 'Ankit Garg SDK',
            organisation_name: null,
            route:
              'route://member_community_profile?community_id=50421&member_id=3563',
            state: 1,
            updated_at: 1668687647,
            user_unique_id: '53208f29-5d15-473e-ab70-5fd77605be0f',
          },
          reactions: [],
          state: 0,
          temporary_id: '-1790086038',
        },
        unseen_conversation_count: 4,
      },
    ],
    total_pages: 1,
    total_unseen_count: 4,
  },
};
