export const dummyData = {
  success: true,
  my_chatrooms: [
    {
      chatroom: {
        id: 24393,
        title: 'asdasdasdasdasd',
        community_id: 49811,
        answer_text: '',
        share_link: '',
        image_count: 0,
        pdf_count: 0,
        video_count: 0,
        audio_count: 0,
        attachment_count: 0,
        attachments_uploaded: false,
        type: 0,
        date_time: 0,
        duration: 0,
        is_pending: false,
        answers_count: 0,
        attending_count: 0,
        polls_count: 0,
        card_creation_time: '10:14 PM',
        community_name: 'New Web Test',
        date: '13 Jun 2022',
        created_at: '22:14',
        date_epoch: 1655138691,
        is_secret: true,
        auto_follow_done: false,
        is_edited: false,
        is_paid: false,
        access: null,
        online_link_type: null,
        online_link_enable_before: 900000,
        is_private: false,
        has_event_recording: false,
        is_private_member: false,
        include_members_later: true,
        secret_chatroom_participants: [1405, 1260],
        has_been_named: true,
        member_id: 1260,
        image_url_round:
          'https://firebasestorage.googleapis.com/v0/b/collabmates-3d601.appspot.com/o/files%2Fmain_website%2Fgeneric_community_banner.png?alt=media&token=044d32ff-3da7-4d8d-9c83-d3c486b61f7a',
        header: 'asdasdasd asdasdad',
        reactions: [],
        state: 1,
        mute_status: false,
        follow_status: true,
        attending_status: false,
        is_guest: false,
        is_tagged: false,
        secret_chatroom_left: false,
        member: {
          id: 1260,
          name: 'Sanjay kumar 🤖',
          updated_at: 1675423248,
          is_guest: false,
          user_unique_id: '51c87f56-3cb5-4bc6-8018-3f25118632a4',
          organisation_name: null,
          image_url:
            'https://firebasestorage.googleapis.com/v0/b/collabmates-beta.appspot.com/o/files%2Fprofile%2F1260?alt=media&token=3051d5f4-6bf0-4c11-a320-ded686f6c5bf',
          state: 1,
          is_owner: true,
          member_since_epoch: 1625315057,
          route:
            'route://member_community_profile?community_id=49811&member_id=1260',
          member_since: 'Member since Jul 03 2021',
          custom_intro_text: 'Created this community on 03 Jul 2021',
        },
        images: [],
        pdf: [],
        audios: [],
        videos: [],
        attachments: [],
      },
      community: {
        id: 49811,
        name: 'New Web Test',
        purpose:
          'Hdkhdis djdjd djdjf fjfkf djdjd djdjdjd didjd didkdj djdjdjjd jdjdjdjf',
        image_url:
          'https://firebasestorage.googleapis.com/v0/b/collabmates-beta.appspot.com/o/files%2Fcommunity%2Fimage_community_default?alt=media',
        members_count: 7,
        type: 4,
        sub_type: 39,
        is_paid: true,
        auto_approval: false,
        grace_period: 345600000,
        is_discoverable: false,
        website_url: 'www.google.com',
        community_category: 'With Marketing',
        referral_enabled: false,
        updated_at: 1647680704,
        fee_membership: 5,
        fee_event: 5,
        fee_payment_pages: 5,
        is_whitelabel: false,
        whitelabel_info: null,
        hide_dm_tab: false,
        is_freemium_community: false,
        community_setting_rights: [
          {
            id: 1,
            title: 'Create chat rooms',
            state: 0,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 2,
            title: 'Create polls',
            state: 1,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 3,
            title: 'Create events',
            state: 2,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 4,
            title: 'Respond in chat rooms',
            state: 3,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 6,
            title: 'Auto-approve created chat rooms',
            sub_title:
              "If auto-approved, member's chat rooms will be posted instantly and would not need any approval.",
            state: 5,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 7,
            title: 'Create secret chat rooms',
            state: 6,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 8,
            title: 'Direct messages',
            sub_title:
              'Direct messaging can happen only between a community manager and a community member (not among 2 members).',
            state: 7,
            is_selected: false,
            is_locked: false,
          },
        ],
      },
      is_draft: false,
      last_conversation: {
        id: 243328,
        answer: 'https://github.com/jhen0409/react-native-debugger',
        state: 0,
        is_edited: false,
        created_at: 1675422636488,
        has_files: false,
        attachment_count: 0,
        attachments_uploaded: false,
        chatroom_id: 24393,
        community_id: 49811,
        created_epoch: 1675422636488,
        og_tags: {
          title:
            'GitHub - jhen0409/react-native-debugger: The standalone app based on official debugger of React Native, and includes React Inspector / Redux DevTools',
          image:
            'https://opengraph.githubassets.com/91d17fba62067b729e443acca1891a88ae80c6048204bf5b8f9afba71f306635/jhen0409/react-native-debugger',
          description:
            'The standalone app based on official debugger of React Native, and includes React Inspector / Redux DevTools - GitHub - jhen0409/react-native-debugger: The standalone app based on official debugger...',
          url: 'https://github.com/jhen0409/react-native-debugger',
        },
        member: {
          id: 1260,
          name: 'Sanjay kumar 🤖',
          updated_at: 1675423248,
          is_guest: false,
          user_unique_id: '51c87f56-3cb5-4bc6-8018-3f25118632a4',
          organisation_name: null,
          image_url:
            'https://firebasestorage.googleapis.com/v0/b/collabmates-beta.appspot.com/o/files%2Fprofile%2F1260?alt=media&token=3051d5f4-6bf0-4c11-a320-ded686f6c5bf',
          state: 1,
          is_owner: true,
          member_since_epoch: 1625315057,
          route:
            'route://member_community_profile?community_id=49811&member_id=1260',
          member_since: 'Member since Jul 03 2021',
          custom_intro_text: 'Created this community on 03 Jul 2021',
        },
        date: '03 Feb 2023',
        reactions: [],
      },
      second_last_conversation: {
        id: 138245,
        answer: 'news',
        state: 0,
        is_edited: false,
        created_at: 1663838873398,
        has_files: false,
        attachment_count: 0,
        attachments_uploaded: false,
        chatroom_id: 24393,
        community_id: 49811,
        created_epoch: 1663838873398,
        member: {
          id: 1260,
          name: 'Sanjay kumar 🤖',
          updated_at: 1675423248,
          is_guest: false,
          user_unique_id: '51c87f56-3cb5-4bc6-8018-3f25118632a4',
          organisation_name: null,
          image_url:
            'https://firebasestorage.googleapis.com/v0/b/collabmates-beta.appspot.com/o/files%2Fprofile%2F1260?alt=media&token=3051d5f4-6bf0-4c11-a320-ded686f6c5bf',
          state: 1,
          is_owner: true,
          member_since_epoch: 1625315057,
          route:
            'route://member_community_profile?community_id=49811&member_id=1260',
          member_since: 'Member since Jul 03 2021',
          custom_intro_text: 'Created this community on 03 Jul 2021',
        },
        date: '22 Sep 2022',
        reactions: [],
      },
      unseen_conversation_count: 0,
      last_conversation_time: '16:40',
      conversation_users: [],
      member_right_states: [0, 1, 2, 3, 5, 6],
      member_state: 1,
    },
    {
      chatroom: {
        id: 28384,
        title: 'Test new single event',
        community_id: 49811,
        answer_text: '',
        share_link: '',
        image_count: 0,
        pdf_count: 0,
        video_count: 0,
        audio_count: 0,
        attachment_count: 1,
        attachments_uploaded: true,
        type: 2,
        date_time: 1665657047000,
        duration: 0,
        is_pending: false,
        answers_count: 0,
        attending_count: 0,
        polls_count: 0,
        card_creation_time: '04:01 PM',
        community_name: 'New Web Test',
        date: '12 Oct 2022',
        created_at: '16:01',
        date_epoch: 1665570662,
        is_secret: false,
        auto_follow_done: false,
        is_edited: false,
        is_paid: false,
        access: 1,
        online_link_type: 1,
        online_link_enable_before: 900000,
        is_private: false,
        has_event_recording: false,
        is_private_member: false,
        include_members_later: true,
        has_been_named: true,
        member_id: 1260,
        image_url_round:
          'https://firebasestorage.googleapis.com/v0/b/collabmates-3d601.appspot.com/o/files%2Fmain_website%2Fgeneric_community_banner.png?alt=media&token=044d32ff-3da7-4d8d-9c83-d3c486b61f7a',
        end_date: 1665678647000,
        about: 'sdklfj sldkfjls dkjflskd fjlskdjf lskdjflskdjfsdfsdf',
        header: 'Test new single event',
        reactions: [],
        state: 1,
        mute_status: false,
        follow_status: true,
        attending_status: true,
        is_guest: false,
        is_tagged: false,
        secret_chatroom_left: false,
        member: {
          id: 1260,
          name: 'Sanjay kumar 🤖',
          updated_at: 1675423248,
          is_guest: false,
          user_unique_id: '51c87f56-3cb5-4bc6-8018-3f25118632a4',
          organisation_name: null,
          image_url:
            'https://firebasestorage.googleapis.com/v0/b/collabmates-beta.appspot.com/o/files%2Fprofile%2F1260?alt=media&token=3051d5f4-6bf0-4c11-a320-ded686f6c5bf',
          state: 1,
          is_owner: true,
          member_since_epoch: 1625315057,
          route:
            'route://member_community_profile?community_id=49811&member_id=1260',
          member_since: 'Member since Jul 03 2021',
          custom_intro_text: 'Created this community on 03 Jul 2021',
        },
        images: [
          {
            image_url:
              'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/28384/event-28384',
            index: null,
            type: 'image',
          },
        ],
        pdf: [],
        audios: [],
        videos: [],
        attachments: [
          {
            url: 'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/28384/event-28384',
            index: null,
            type: 'image',
          },
        ],
      },
      community: {
        id: 49811,
        name: 'New Web Test',
        purpose:
          'Hdkhdis djdjd djdjf fjfkf djdjd djdjdjd didjd didkdj djdjdjjd jdjdjdjf',
        image_url:
          'https://firebasestorage.googleapis.com/v0/b/collabmates-beta.appspot.com/o/files%2Fcommunity%2Fimage_community_default?alt=media',
        members_count: 7,
        type: 4,
        sub_type: 39,
        is_paid: true,
        auto_approval: false,
        grace_period: 345600000,
        is_discoverable: false,
        website_url: 'www.google.com',
        community_category: 'With Marketing',
        referral_enabled: false,
        updated_at: 1647680704,
        fee_membership: 5,
        fee_event: 5,
        fee_payment_pages: 5,
        is_whitelabel: false,
        whitelabel_info: null,
        hide_dm_tab: false,
        is_freemium_community: false,
        community_setting_rights: [
          {
            id: 1,
            title: 'Create chat rooms',
            state: 0,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 2,
            title: 'Create polls',
            state: 1,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 3,
            title: 'Create events',
            state: 2,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 4,
            title: 'Respond in chat rooms',
            state: 3,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 6,
            title: 'Auto-approve created chat rooms',
            sub_title:
              "If auto-approved, member's chat rooms will be posted instantly and would not need any approval.",
            state: 5,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 7,
            title: 'Create secret chat rooms',
            state: 6,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 8,
            title: 'Direct messages',
            sub_title:
              'Direct messaging can happen only between a community manager and a community member (not among 2 members).',
            state: 7,
            is_selected: false,
            is_locked: false,
          },
        ],
      },
      is_draft: false,
      last_conversation: {
        id: 243327,
        answer: 'Yes!',
        state: 0,
        is_edited: false,
        created_at: 1675421963854,
        has_files: false,
        attachment_count: 0,
        attachments_uploaded: false,
        chatroom_id: 28384,
        community_id: 49811,
        created_epoch: 1675421963854,
        member: {
          id: 1260,
          name: 'Sanjay kumar 🤖',
          updated_at: 1675423248,
          is_guest: false,
          user_unique_id: '51c87f56-3cb5-4bc6-8018-3f25118632a4',
          organisation_name: null,
          image_url:
            'https://firebasestorage.googleapis.com/v0/b/collabmates-beta.appspot.com/o/files%2Fprofile%2F1260?alt=media&token=3051d5f4-6bf0-4c11-a320-ded686f6c5bf',
          state: 1,
          is_owner: true,
          member_since_epoch: 1625315057,
          route:
            'route://member_community_profile?community_id=49811&member_id=1260',
          member_since: 'Member since Jul 03 2021',
          custom_intro_text: 'Created this community on 03 Jul 2021',
        },
        date: '03 Feb 2023',
        reply_conversation: 141943,
        reply_conversation_object: {
          id: 141943,
          answer: 'sdfsdfsd dfs dfsdfsd sdfsdf',
          state: 0,
          is_edited: false,
          created_at: 1665575170075,
          has_files: false,
          attachment_count: 0,
          attachments_uploaded: false,
          chatroom_id: 28384,
          community_id: 49811,
          created_epoch: 1665575170075,
          member: {
            id: 1260,
            name: 'Sanjay kumar 🤖',
            updated_at: 1675423248,
            is_guest: false,
            user_unique_id: '51c87f56-3cb5-4bc6-8018-3f25118632a4',
            organisation_name: null,
            image_url:
              'https://firebasestorage.googleapis.com/v0/b/collabmates-beta.appspot.com/o/files%2Fprofile%2F1260?alt=media&token=3051d5f4-6bf0-4c11-a320-ded686f6c5bf',
            state: 1,
            is_owner: true,
            member_since_epoch: 1625315057,
            route:
              'route://member_community_profile?community_id=49811&member_id=1260',
            member_since: 'Member since Jul 03 2021',
            custom_intro_text: 'Created this community on 03 Jul 2021',
          },
          date: '12 Oct 2022',
          reactions: [],
        },
        reactions: [],
      },
      second_last_conversation: {
        id: 141944,
        answer: 'test',
        state: 0,
        is_edited: false,
        created_at: 1665575174373,
        has_files: false,
        attachment_count: 0,
        attachments_uploaded: false,
        chatroom_id: 28384,
        community_id: 49811,
        created_epoch: 1665575174373,
        member: {
          id: 1260,
          name: 'Sanjay kumar 🤖',
          updated_at: 1675423248,
          is_guest: false,
          user_unique_id: '51c87f56-3cb5-4bc6-8018-3f25118632a4',
          organisation_name: null,
          image_url:
            'https://firebasestorage.googleapis.com/v0/b/collabmates-beta.appspot.com/o/files%2Fprofile%2F1260?alt=media&token=3051d5f4-6bf0-4c11-a320-ded686f6c5bf',
          state: 1,
          is_owner: true,
          member_since_epoch: 1625315057,
          route:
            'route://member_community_profile?community_id=49811&member_id=1260',
          member_since: 'Member since Jul 03 2021',
          custom_intro_text: 'Created this community on 03 Jul 2021',
        },
        date: '12 Oct 2022',
        reactions: [],
      },
      unseen_conversation_count: 0,
      last_conversation_time: '16:29',
      conversation_users: [],
      member_right_states: [0, 1, 2, 3, 5, 6],
      member_state: 1,
    },
    {
      chatroom: {
        id: 23098,
        title: 'paid 100% 2',
        community_id: 49811,
        answer_text: '',
        share_link: '',
        image_count: 0,
        pdf_count: 0,
        video_count: 0,
        audio_count: 0,
        attachment_count: 1,
        attachments_uploaded: true,
        type: 2,
        date_time: 1648038600000,
        duration: 0,
        is_pending: false,
        answers_count: 0,
        attending_count: 0,
        polls_count: 0,
        card_creation_time: '01:44 PM',
        community_name: 'New Web Test',
        date: '21 Mar 2022',
        created_at: '13:44',
        date_epoch: 1647850481,
        is_secret: false,
        auto_follow_done: false,
        is_edited: false,
        is_paid: true,
        access: 1,
        online_link_type: null,
        online_link_enable_before: 900000,
        is_private: false,
        has_event_recording: false,
        is_private_member: false,
        include_members_later: true,
        has_been_named: true,
        member_id: 1260,
        image_url_round:
          'https://firebasestorage.googleapis.com/v0/b/collabmates-3d601.appspot.com/o/files%2Fmain_website%2Fgeneric_community_banner.png?alt=media&token=044d32ff-3da7-4d8d-9c83-d3c486b61f7a',
        end_date: 1648042200000,
        about: 'new',
        event_payment_link:
          'https://betaweb.likeminds.community/event_pay?event_plan_id=ba674818-c673-4e05-a339-6037b5a538a7&chatroom_id=23098&community_id=49811',
        header: 'paid 100% 2',
        reactions: [],
        state: 1,
        mute_status: false,
        follow_status: true,
        attending_status: true,
        is_guest: false,
        is_tagged: false,
        secret_chatroom_left: false,
        member: {
          id: 1260,
          name: 'Sanjay kumar 🤖',
          updated_at: 1675423248,
          is_guest: false,
          user_unique_id: '51c87f56-3cb5-4bc6-8018-3f25118632a4',
          organisation_name: null,
          image_url:
            'https://firebasestorage.googleapis.com/v0/b/collabmates-beta.appspot.com/o/files%2Fprofile%2F1260?alt=media&token=3051d5f4-6bf0-4c11-a320-ded686f6c5bf',
          state: 1,
          is_owner: true,
          member_since_epoch: 1625315057,
          route:
            'route://member_community_profile?community_id=49811&member_id=1260',
          member_since: 'Member since Jul 03 2021',
          custom_intro_text: 'Created this community on 03 Jul 2021',
        },
        images: [
          {
            image_url:
              'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/23098/event-23098',
            index: null,
            type: 'image',
          },
        ],
        pdf: [],
        audios: [],
        videos: [],
        attachments: [
          {
            url: 'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/23098/event-23098',
            index: null,
            type: 'image',
          },
        ],
      },
      community: {
        id: 49811,
        name: 'New Web Test',
        purpose:
          'Hdkhdis djdjd djdjf fjfkf djdjd djdjdjd didjd didkdj djdjdjjd jdjdjdjf',
        image_url:
          'https://firebasestorage.googleapis.com/v0/b/collabmates-beta.appspot.com/o/files%2Fcommunity%2Fimage_community_default?alt=media',
        members_count: 7,
        type: 4,
        sub_type: 39,
        is_paid: true,
        auto_approval: false,
        grace_period: 345600000,
        is_discoverable: false,
        website_url: 'www.google.com',
        community_category: 'With Marketing',
        referral_enabled: false,
        updated_at: 1647680704,
        fee_membership: 5,
        fee_event: 5,
        fee_payment_pages: 5,
        is_whitelabel: false,
        whitelabel_info: null,
        hide_dm_tab: false,
        is_freemium_community: false,
        community_setting_rights: [
          {
            id: 1,
            title: 'Create chat rooms',
            state: 0,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 2,
            title: 'Create polls',
            state: 1,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 3,
            title: 'Create events',
            state: 2,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 4,
            title: 'Respond in chat rooms',
            state: 3,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 6,
            title: 'Auto-approve created chat rooms',
            sub_title:
              "If auto-approved, member's chat rooms will be posted instantly and would not need any approval.",
            state: 5,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 7,
            title: 'Create secret chat rooms',
            state: 6,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 8,
            title: 'Direct messages',
            sub_title:
              'Direct messaging can happen only between a community manager and a community member (not among 2 members).',
            state: 7,
            is_selected: false,
            is_locked: false,
          },
        ],
      },
      is_draft: false,
      last_conversation: {
        id: 243326,
        answer: '',
        state: 0,
        is_edited: false,
        created_at: 1675421887361,
        has_files: true,
        attachment_count: 1,
        attachments_uploaded: true,
        chatroom_id: 23098,
        community_id: 49811,
        created_epoch: 1675421887361,
        images: [],
        videos: [],
        audios: [],
        pdf: [
          {
            pdf_file:
              'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/23098/conversation/243326/SignalPresentation.pdf',
            index: 0,
            type: 'pdf',
            name: 'SignalPresentation.pdf',
            meta: {
              duration: null,
              size: 12917556,
              number_of_page: 79,
            },
          },
        ],
        attachments: [
          {
            url: 'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/23098/conversation/243326/SignalPresentation.pdf',
            index: 0,
            type: 'pdf',
            name: 'SignalPresentation.pdf',
            meta: {
              duration: null,
              size: 12917556,
              number_of_page: 79,
            },
          },
        ],
        member: {
          id: 1260,
          name: 'Sanjay kumar 🤖',
          updated_at: 1675423248,
          is_guest: false,
          user_unique_id: '51c87f56-3cb5-4bc6-8018-3f25118632a4',
          organisation_name: null,
          image_url:
            'https://firebasestorage.googleapis.com/v0/b/collabmates-beta.appspot.com/o/files%2Fprofile%2F1260?alt=media&token=3051d5f4-6bf0-4c11-a320-ded686f6c5bf',
          state: 1,
          is_owner: true,
          member_since_epoch: 1625315057,
          route:
            'route://member_community_profile?community_id=49811&member_id=1260',
          member_since: 'Member since Jul 03 2021',
          custom_intro_text: 'Created this community on 03 Jul 2021',
        },
        date: '03 Feb 2023',
        reactions: [],
      },
      second_last_conversation: {
        id: 242936,
        answer: '',
        state: 0,
        is_edited: false,
        created_at: 1675173895359,
        has_files: true,
        attachment_count: 1,
        attachments_uploaded: true,
        chatroom_id: 23098,
        community_id: 49811,
        created_epoch: 1675173895359,
        images: [
          {
            image_url:
              'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/23098/conversation/242936/Screenshot%202023-01-31%20at%207.19.35%20PM.png',
            index: 0,
            type: 'image',
            name: 'Screenshot 2023-01-31 at 7.19.35 PM.png',
            meta: {
              size: 380452,
              number_of_page: null,
            },
          },
        ],
        videos: [],
        audios: [],
        pdf: [],
        attachments: [
          {
            url: 'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/23098/conversation/242936/Screenshot%202023-01-31%20at%207.19.35%20PM.png',
            index: 0,
            type: 'image',
            name: 'Screenshot 2023-01-31 at 7.19.35 PM.png',
            meta: {
              size: 380452,
              number_of_page: null,
            },
          },
        ],
        member: {
          id: 1260,
          name: 'Sanjay kumar 🤖',
          updated_at: 1675423248,
          is_guest: false,
          user_unique_id: '51c87f56-3cb5-4bc6-8018-3f25118632a4',
          organisation_name: null,
          image_url:
            'https://firebasestorage.googleapis.com/v0/b/collabmates-beta.appspot.com/o/files%2Fprofile%2F1260?alt=media&token=3051d5f4-6bf0-4c11-a320-ded686f6c5bf',
          state: 1,
          is_owner: true,
          member_since_epoch: 1625315057,
          route:
            'route://member_community_profile?community_id=49811&member_id=1260',
          member_since: 'Member since Jul 03 2021',
          custom_intro_text: 'Created this community on 03 Jul 2021',
        },
        date: '31 Jan 2023',
        reactions: [],
      },
      unseen_conversation_count: 0,
      last_conversation_time: '16:28',
      conversation_users: [],
      member_right_states: [0, 1, 2, 3, 5, 6],
      member_state: 1,
    },
    {
      chatroom: {
        id: 21130,
        title: 'testing26_DuplicateChatroom',
        community_id: 49811,
        answer_text: '',
        share_link: '',
        image_count: 0,
        pdf_count: 0,
        video_count: 0,
        audio_count: 0,
        attachment_count: 0,
        attachments_uploaded: false,
        type: 0,
        date_time: 0,
        duration: 0,
        is_pending: false,
        answers_count: 0,
        attending_count: 0,
        polls_count: 0,
        card_creation_time: '06:49 PM',
        community_name: 'New Web Test',
        date: '07 Jan 2022',
        created_at: '18:49',
        date_epoch: 1641561562,
        is_secret: false,
        auto_follow_done: false,
        is_edited: false,
        is_paid: false,
        access: 1,
        online_link_type: null,
        online_link_enable_before: 900000,
        is_private: false,
        has_event_recording: false,
        is_private_member: false,
        include_members_later: true,
        image_url_round:
          'https://firebasestorage.googleapis.com/v0/b/collabmates-3d601.appspot.com/o/files%2Fmain_website%2Fgeneric_community_banner.png?alt=media&token=044d32ff-3da7-4d8d-9c83-d3c486b61f7a',
        header: 'testing26_DuplicateChatroom',
        reactions: [
          {
            member: {
              id: 1421,
              name: 'Shashank',
              image_url:
                'https://firebasestorage.googleapis.com/v0/b/collabmates-beta.appspot.com/o/files%2Fprofile%2F9944428930?alt=media&token=80dfd85e-3b50-4baa-8c6a-518a6287a4af',
            },
            reaction: '😮',
            updated_at: 1642412236945,
          },
        ],
        state: 1,
        mute_status: false,
        follow_status: true,
        attending_status: false,
        is_guest: false,
        is_tagged: false,
        secret_chatroom_left: false,
        member: {
          id: 1421,
          name: 'Shashank',
          updated_at: 1653461505,
          is_guest: false,
          user_unique_id: 'eeb2d0d3-6d30-4b06-8d73-142f6520ba1f',
          organisation_name: null,
          image_url:
            'https://firebasestorage.googleapis.com/v0/b/collabmates-beta.appspot.com/o/files%2Fprofile%2F9944428930?alt=media&token=80dfd85e-3b50-4baa-8c6a-518a6287a4af',
          state: 4,
          is_owner: false,
          member_since_epoch: 1641456057,
          route:
            'route://member_community_profile?community_id=49811&member_id=1421',
          member_since: 'Member since Jan 06 2022',
          custom_intro_text: 'Profile does not exist',
          custom_click_text:
            "The profile you are trying to access does not exist. Shashank's membership expired on 29 Jun 2022",
          remove_state: 2,
        },
        images: [],
        pdf: [],
        audios: [],
        videos: [],
        attachments: [],
      },
      community: {
        id: 49811,
        name: 'New Web Test',
        purpose:
          'Hdkhdis djdjd djdjf fjfkf djdjd djdjdjd didjd didkdj djdjdjjd jdjdjdjf',
        image_url:
          'https://firebasestorage.googleapis.com/v0/b/collabmates-beta.appspot.com/o/files%2Fcommunity%2Fimage_community_default?alt=media',
        members_count: 7,
        type: 4,
        sub_type: 39,
        is_paid: true,
        auto_approval: false,
        grace_period: 345600000,
        is_discoverable: false,
        website_url: 'www.google.com',
        community_category: 'With Marketing',
        referral_enabled: false,
        updated_at: 1647680704,
        fee_membership: 5,
        fee_event: 5,
        fee_payment_pages: 5,
        is_whitelabel: false,
        whitelabel_info: null,
        hide_dm_tab: false,
        is_freemium_community: false,
        community_setting_rights: [
          {
            id: 1,
            title: 'Create chat rooms',
            state: 0,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 2,
            title: 'Create polls',
            state: 1,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 3,
            title: 'Create events',
            state: 2,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 4,
            title: 'Respond in chat rooms',
            state: 3,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 6,
            title: 'Auto-approve created chat rooms',
            sub_title:
              "If auto-approved, member's chat rooms will be posted instantly and would not need any approval.",
            state: 5,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 7,
            title: 'Create secret chat rooms',
            state: 6,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 8,
            title: 'Direct messages',
            sub_title:
              'Direct messaging can happen only between a community manager and a community member (not among 2 members).',
            state: 7,
            is_selected: false,
            is_locked: false,
          },
        ],
      },
      is_draft: false,
      last_conversation: {
        id: 243325,
        answer:
          '<<Sanjay kumar 🤖|route://member/1260>> <<Ishaan Jain|route://member/1003>> Hey google.com',
        state: 0,
        is_edited: false,
        created_at: 1675421848540,
        has_files: false,
        attachment_count: 0,
        attachments_uploaded: false,
        chatroom_id: 21130,
        community_id: 49811,
        created_epoch: 1675421848540,
        member: {
          id: 1260,
          name: 'Sanjay kumar 🤖',
          updated_at: 1675423248,
          is_guest: false,
          user_unique_id: '51c87f56-3cb5-4bc6-8018-3f25118632a4',
          organisation_name: null,
          image_url:
            'https://firebasestorage.googleapis.com/v0/b/collabmates-beta.appspot.com/o/files%2Fprofile%2F1260?alt=media&token=3051d5f4-6bf0-4c11-a320-ded686f6c5bf',
          state: 1,
          is_owner: true,
          member_since_epoch: 1625315057,
          route:
            'route://member_community_profile?community_id=49811&member_id=1260',
          member_since: 'Member since Jul 03 2021',
          custom_intro_text: 'Created this community on 03 Jul 2021',
        },
        date: '03 Feb 2023',
        reactions: [],
      },
      second_last_conversation: {
        id: 242945,
        answer: 'new test',
        state: 0,
        is_edited: false,
        created_at: 1675182263964,
        has_files: false,
        attachment_count: 0,
        attachments_uploaded: false,
        chatroom_id: 21130,
        community_id: 49811,
        created_epoch: 1675182263964,
        member: {
          id: 1260,
          name: 'Sanjay kumar 🤖',
          updated_at: 1675423248,
          is_guest: false,
          user_unique_id: '51c87f56-3cb5-4bc6-8018-3f25118632a4',
          organisation_name: null,
          image_url:
            'https://firebasestorage.googleapis.com/v0/b/collabmates-beta.appspot.com/o/files%2Fprofile%2F1260?alt=media&token=3051d5f4-6bf0-4c11-a320-ded686f6c5bf',
          state: 1,
          is_owner: true,
          member_since_epoch: 1625315057,
          route:
            'route://member_community_profile?community_id=49811&member_id=1260',
          member_since: 'Member since Jul 03 2021',
          custom_intro_text: 'Created this community on 03 Jul 2021',
        },
        date: '31 Jan 2023',
        reactions: [],
      },
      unseen_conversation_count: 0,
      last_conversation_time: '16:27',
      conversation_users: [
        {
          id: 1260,
          name: 'Sanjay kumar 🤖',
          image_url:
            'https://firebasestorage.googleapis.com/v0/b/collabmates-beta.appspot.com/o/files%2Fprofile%2F1260?alt=media&token=3051d5f4-6bf0-4c11-a320-ded686f6c5bf',
        },
      ],
      member_right_states: [0, 1, 2, 3, 5, 6],
      member_state: 1,
    },
    {
      chatroom: {
        id: 23094,
        title: 'paid 100%',
        community_id: 49811,
        answer_text: '',
        share_link: '',
        image_count: 0,
        pdf_count: 0,
        video_count: 0,
        audio_count: 0,
        attachment_count: 1,
        attachments_uploaded: true,
        type: 2,
        date_time: 1648038600000,
        duration: 0,
        is_pending: false,
        answers_count: 0,
        attending_count: 0,
        polls_count: 0,
        card_creation_time: '01:35 PM',
        community_name: 'New Web Test',
        date: '21 Mar 2022',
        created_at: '13:35',
        date_epoch: 1647849940,
        is_secret: false,
        auto_follow_done: false,
        is_edited: false,
        is_paid: true,
        access: 1,
        online_link_type: null,
        online_link_enable_before: 900000,
        is_private: false,
        has_event_recording: false,
        is_private_member: false,
        include_members_later: true,
        has_been_named: true,
        member_id: 1260,
        image_url_round:
          'https://firebasestorage.googleapis.com/v0/b/collabmates-3d601.appspot.com/o/files%2Fmain_website%2Fgeneric_community_banner.png?alt=media&token=044d32ff-3da7-4d8d-9c83-d3c486b61f7a',
        end_date: 1648042200000,
        about: 'new',
        event_payment_link:
          'https://betaweb.likeminds.community/event_pay?event_plan_id=2e537735-0dfa-4700-8d05-045567d50ed5&chatroom_id=23094&community_id=49811',
        header: 'paid 100%',
        reactions: [],
        state: 1,
        mute_status: false,
        follow_status: true,
        attending_status: true,
        is_guest: false,
        is_tagged: false,
        secret_chatroom_left: false,
        member: {
          id: 1260,
          name: 'Sanjay kumar 🤖',
          updated_at: 1675423248,
          is_guest: false,
          user_unique_id: '51c87f56-3cb5-4bc6-8018-3f25118632a4',
          organisation_name: null,
          image_url:
            'https://firebasestorage.googleapis.com/v0/b/collabmates-beta.appspot.com/o/files%2Fprofile%2F1260?alt=media&token=3051d5f4-6bf0-4c11-a320-ded686f6c5bf',
          state: 1,
          is_owner: true,
          member_since_epoch: 1625315057,
          route:
            'route://member_community_profile?community_id=49811&member_id=1260',
          member_since: 'Member since Jul 03 2021',
          custom_intro_text: 'Created this community on 03 Jul 2021',
        },
        images: [
          {
            image_url:
              'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/23094/event-23094',
            index: null,
            type: 'image',
          },
        ],
        pdf: [],
        audios: [],
        videos: [],
        attachments: [
          {
            url: 'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/23094/event-23094',
            index: null,
            type: 'image',
          },
        ],
      },
      community: {
        id: 49811,
        name: 'New Web Test',
        purpose:
          'Hdkhdis djdjd djdjf fjfkf djdjd djdjdjd didjd didkdj djdjdjjd jdjdjdjf',
        image_url:
          'https://firebasestorage.googleapis.com/v0/b/collabmates-beta.appspot.com/o/files%2Fcommunity%2Fimage_community_default?alt=media',
        members_count: 7,
        type: 4,
        sub_type: 39,
        is_paid: true,
        auto_approval: false,
        grace_period: 345600000,
        is_discoverable: false,
        website_url: 'www.google.com',
        community_category: 'With Marketing',
        referral_enabled: false,
        updated_at: 1647680704,
        fee_membership: 5,
        fee_event: 5,
        fee_payment_pages: 5,
        is_whitelabel: false,
        whitelabel_info: null,
        hide_dm_tab: false,
        is_freemium_community: false,
        community_setting_rights: [
          {
            id: 1,
            title: 'Create chat rooms',
            state: 0,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 2,
            title: 'Create polls',
            state: 1,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 3,
            title: 'Create events',
            state: 2,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 4,
            title: 'Respond in chat rooms',
            state: 3,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 6,
            title: 'Auto-approve created chat rooms',
            sub_title:
              "If auto-approved, member's chat rooms will be posted instantly and would not need any approval.",
            state: 5,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 7,
            title: 'Create secret chat rooms',
            state: 6,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 8,
            title: 'Direct messages',
            sub_title:
              'Direct messaging can happen only between a community manager and a community member (not among 2 members).',
            state: 7,
            is_selected: false,
            is_locked: false,
          },
        ],
      },
      is_draft: false,
      last_conversation: {
        id: 243298,
        answer: '',
        state: 0,
        is_edited: false,
        created_at: 1675419888596,
        has_files: true,
        attachment_count: 3,
        attachments_uploaded: true,
        chatroom_id: 23094,
        community_id: 49811,
        created_epoch: 1675419888596,
        images: [
          {
            image_url:
              'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/23094/conversation/243298/back_arrow3x.png',
            index: 0,
            type: 'image',
            name: 'back_arrow3x.png',
            meta: {
              size: 1789,
              number_of_page: null,
            },
          },
          {
            image_url:
              'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/23094/conversation/243298/cross_icon3x.png',
            index: 1,
            type: 'image',
            name: 'cross_icon3x.png',
            meta: {
              size: 490,
              number_of_page: null,
            },
          },
          {
            image_url:
              'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/23094/conversation/243298/down_arrow3x.png',
            index: 2,
            type: 'image',
            name: 'down_arrow3x.png',
            meta: {
              size: 521,
              number_of_page: null,
            },
          },
        ],
        videos: [],
        audios: [],
        pdf: [],
        attachments: [
          {
            url: 'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/23094/conversation/243298/back_arrow3x.png',
            index: 0,
            type: 'image',
            name: 'back_arrow3x.png',
            meta: {
              size: 1789,
              number_of_page: null,
            },
          },
          {
            url: 'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/23094/conversation/243298/cross_icon3x.png',
            index: 1,
            type: 'image',
            name: 'cross_icon3x.png',
            meta: {
              size: 490,
              number_of_page: null,
            },
          },
          {
            url: 'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/23094/conversation/243298/down_arrow3x.png',
            index: 2,
            type: 'image',
            name: 'down_arrow3x.png',
            meta: {
              size: 521,
              number_of_page: null,
            },
          },
        ],
        member: {
          id: 1260,
          name: 'Sanjay kumar 🤖',
          updated_at: 1675423248,
          is_guest: false,
          user_unique_id: '51c87f56-3cb5-4bc6-8018-3f25118632a4',
          organisation_name: null,
          image_url:
            'https://firebasestorage.googleapis.com/v0/b/collabmates-beta.appspot.com/o/files%2Fprofile%2F1260?alt=media&token=3051d5f4-6bf0-4c11-a320-ded686f6c5bf',
          state: 1,
          is_owner: true,
          member_since_epoch: 1625315057,
          route:
            'route://member_community_profile?community_id=49811&member_id=1260',
          member_since: 'Member since Jul 03 2021',
          custom_intro_text: 'Created this community on 03 Jul 2021',
        },
        date: '03 Feb 2023',
        reactions: [],
      },
      second_last_conversation: {
        id: 243297,
        answer: '<<Sanjay kumar 🤖|route://member/1260>> google.com',
        state: 0,
        is_edited: false,
        created_at: 1675419808880,
        has_files: false,
        attachment_count: 0,
        attachments_uploaded: false,
        chatroom_id: 23094,
        community_id: 49811,
        created_epoch: 1675419808880,
        og_tags: {
          title: 'Google',
          image: '',
          description: '',
          url: 'google.com',
        },
        member: {
          id: 1260,
          name: 'Sanjay kumar 🤖',
          updated_at: 1675423248,
          is_guest: false,
          user_unique_id: '51c87f56-3cb5-4bc6-8018-3f25118632a4',
          organisation_name: null,
          image_url:
            'https://firebasestorage.googleapis.com/v0/b/collabmates-beta.appspot.com/o/files%2Fprofile%2F1260?alt=media&token=3051d5f4-6bf0-4c11-a320-ded686f6c5bf',
          state: 1,
          is_owner: true,
          member_since_epoch: 1625315057,
          route:
            'route://member_community_profile?community_id=49811&member_id=1260',
          member_since: 'Member since Jul 03 2021',
          custom_intro_text: 'Created this community on 03 Jul 2021',
        },
        date: '03 Feb 2023',
        reactions: [],
      },
      unseen_conversation_count: 0,
      last_conversation_time: '15:54',
      conversation_users: [],
      member_right_states: [0, 1, 2, 3, 5, 6],
      member_state: 1,
    },
    {
      chatroom: {
        id: 21819,
        title: 'testingFinal123',
        community_id: 49811,
        answer_text: '',
        share_link: '',
        image_count: 1,
        pdf_count: 0,
        video_count: 0,
        audio_count: 0,
        attachment_count: 1,
        attachments_uploaded: true,
        type: 0,
        date_time: 0,
        duration: 0,
        is_pending: false,
        answers_count: 0,
        attending_count: 0,
        polls_count: 0,
        card_creation_time: '04:35 PM',
        community_name: 'New Web Test',
        date: '25 Jan 2022',
        created_at: '16:35',
        date_epoch: 1643108743,
        is_secret: true,
        auto_follow_done: false,
        is_edited: false,
        is_paid: false,
        access: 1,
        online_link_type: null,
        online_link_enable_before: 900000,
        is_private: false,
        has_event_recording: false,
        is_private_member: false,
        include_members_later: true,
        secret_chatroom_participants: [1421, 1260],
        has_been_named: true,
        member_id: 1260,
        image_url_round:
          'https://firebasestorage.googleapis.com/v0/b/collabmates-3d601.appspot.com/o/files%2Fmain_website%2Fgeneric_community_banner.png?alt=media&token=044d32ff-3da7-4d8d-9c83-d3c486b61f7a',
        header: 'testingFinal123',
        reactions: [],
        state: 1,
        mute_status: false,
        follow_status: true,
        attending_status: false,
        is_guest: false,
        is_tagged: false,
        secret_chatroom_left: false,
        member: {
          id: 1260,
          name: 'Sanjay kumar 🤖',
          updated_at: 1675423248,
          is_guest: false,
          user_unique_id: '51c87f56-3cb5-4bc6-8018-3f25118632a4',
          organisation_name: null,
          image_url:
            'https://firebasestorage.googleapis.com/v0/b/collabmates-beta.appspot.com/o/files%2Fprofile%2F1260?alt=media&token=3051d5f4-6bf0-4c11-a320-ded686f6c5bf',
          state: 1,
          is_owner: true,
          member_since_epoch: 1625315057,
          route:
            'route://member_community_profile?community_id=49811&member_id=1260',
          member_since: 'Member since Jul 03 2021',
          custom_intro_text: 'Created this community on 03 Jul 2021',
        },
        images: [
          {
            image_url:
              'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/21819/conversation/image-2021-05-22-00-56-54-552.png',
            index: 0,
            type: 'image',
            name: 'image-2021-05-22-00-56-54-552.png',
          },
        ],
        pdf: [],
        audios: [],
        videos: [],
        attachments: [
          {
            url: 'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/21819/conversation/image-2021-05-22-00-56-54-552.png',
            index: 0,
            type: 'image',
            name: 'image-2021-05-22-00-56-54-552.png',
          },
        ],
      },
      community: {
        id: 49811,
        name: 'New Web Test',
        purpose:
          'Hdkhdis djdjd djdjf fjfkf djdjd djdjdjd didjd didkdj djdjdjjd jdjdjdjf',
        image_url:
          'https://firebasestorage.googleapis.com/v0/b/collabmates-beta.appspot.com/o/files%2Fcommunity%2Fimage_community_default?alt=media',
        members_count: 7,
        type: 4,
        sub_type: 39,
        is_paid: true,
        auto_approval: false,
        grace_period: 345600000,
        is_discoverable: false,
        website_url: 'www.google.com',
        community_category: 'With Marketing',
        referral_enabled: false,
        updated_at: 1647680704,
        fee_membership: 5,
        fee_event: 5,
        fee_payment_pages: 5,
        is_whitelabel: false,
        whitelabel_info: null,
        hide_dm_tab: false,
        is_freemium_community: false,
        community_setting_rights: [
          {
            id: 1,
            title: 'Create chat rooms',
            state: 0,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 2,
            title: 'Create polls',
            state: 1,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 3,
            title: 'Create events',
            state: 2,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 4,
            title: 'Respond in chat rooms',
            state: 3,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 6,
            title: 'Auto-approve created chat rooms',
            sub_title:
              "If auto-approved, member's chat rooms will be posted instantly and would not need any approval.",
            state: 5,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 7,
            title: 'Create secret chat rooms',
            state: 6,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 8,
            title: 'Direct messages',
            sub_title:
              'Direct messaging can happen only between a community manager and a community member (not among 2 members).',
            state: 7,
            is_selected: false,
            is_locked: false,
          },
        ],
      },
      is_draft: false,
      last_conversation: {
        id: 145255,
        answer: 'Tedt',
        state: 0,
        is_edited: false,
        created_at: 1670729630227,
        has_files: false,
        attachment_count: 0,
        attachments_uploaded: false,
        chatroom_id: 21819,
        community_id: 49811,
        created_epoch: 1670729630227,
        deleted_by: 1260,
        member: {
          id: 1260,
          name: 'Sanjay kumar 🤖',
          updated_at: 1675423248,
          is_guest: false,
          user_unique_id: '51c87f56-3cb5-4bc6-8018-3f25118632a4',
          organisation_name: null,
          image_url:
            'https://firebasestorage.googleapis.com/v0/b/collabmates-beta.appspot.com/o/files%2Fprofile%2F1260?alt=media&token=3051d5f4-6bf0-4c11-a320-ded686f6c5bf',
          state: 1,
          is_owner: true,
          member_since_epoch: 1625315057,
          route:
            'route://member_community_profile?community_id=49811&member_id=1260',
          member_since: 'Member since Jul 03 2021',
          custom_intro_text: 'Created this community on 03 Jul 2021',
        },
        date: '11 Dec 2022',
        temporary_id: '8713B32B-D1AF-4413-95E6-88789BE536C0',
        reactions: [],
      },
      second_last_conversation: {
        id: 145068,
        answer: '\n * This is a gif message. Please update your app *',
        state: 0,
        is_edited: false,
        created_at: 1670345497858,
        has_files: true,
        attachment_count: 1,
        attachments_uploaded: true,
        chatroom_id: 21819,
        community_id: 49811,
        created_epoch: 1670345497858,
        images: [],
        videos: [],
        audios: [],
        pdf: [],
        attachments: [
          {
            url: 'https://s3.ap-south-1.amazonaws.com/beta-likeminds-media/D9349DC8-B5FD-4121-87EC-9B2A43CF2A45-13643-00000267C198EAD5.gif',
            index: 0,
            type: 'gif',
            height: 200,
            width: 230,
            thumbnail_url:
              'https://s3.ap-south-1.amazonaws.com/beta-likeminds-media/files/collabcard/21819/conversation/145068/GIF_THUMB_Happy%20I%20Love%20You%20GIF%20by%20GGKT83CC9AE8-93AC-4F79-AEAC-73AC4FC310F7-13643-00000267C10CAA6C.jpeg',
            name: 'Happy I Love You GIF by GGKT',
            meta: {
              size: 222264,
            },
          },
        ],
        member: {
          id: 1260,
          name: 'Sanjay kumar 🤖',
          updated_at: 1675423248,
          is_guest: false,
          user_unique_id: '51c87f56-3cb5-4bc6-8018-3f25118632a4',
          organisation_name: null,
          image_url:
            'https://firebasestorage.googleapis.com/v0/b/collabmates-beta.appspot.com/o/files%2Fprofile%2F1260?alt=media&token=3051d5f4-6bf0-4c11-a320-ded686f6c5bf',
          state: 1,
          is_owner: true,
          member_since_epoch: 1625315057,
          route:
            'route://member_community_profile?community_id=49811&member_id=1260',
          member_since: 'Member since Jul 03 2021',
          custom_intro_text: 'Created this community on 03 Jul 2021',
        },
        date: '06 Dec 2022',
        temporary_id: 'B645D5DC-56D6-4EC2-AF00-B122DD646CBD',
        reactions: [],
      },
      unseen_conversation_count: 0,
      last_conversation_time: '11/12/22',
      conversation_users: [],
      member_right_states: [0, 1, 2, 3, 5, 6],
      member_state: 1,
    },
    {
      chatroom: {
        id: 24181,
        title: 'lkdjf lskdjfl skdjf lkj',
        community_id: 49811,
        answer_text: '',
        share_link: '',
        image_count: 0,
        pdf_count: 0,
        video_count: 0,
        audio_count: 0,
        attachment_count: 0,
        attachments_uploaded: false,
        type: 0,
        date_time: 0,
        duration: 0,
        is_pending: false,
        answers_count: 0,
        attending_count: 0,
        polls_count: 0,
        card_creation_time: '03:23 PM',
        community_name: 'New Web Test',
        date: '07 Jun 2022',
        created_at: '15:23',
        date_epoch: 1654595638,
        is_secret: true,
        auto_follow_done: false,
        is_edited: false,
        is_paid: false,
        access: null,
        online_link_type: null,
        online_link_enable_before: 900000,
        is_private: false,
        has_event_recording: false,
        is_private_member: false,
        include_members_later: true,
        secret_chatroom_participants: [629, 1260],
        has_been_named: true,
        member_id: 1260,
        image_url_round:
          'https://firebasestorage.googleapis.com/v0/b/collabmates-3d601.appspot.com/o/files%2Fmain_website%2Fgeneric_community_banner.png?alt=media&token=044d32ff-3da7-4d8d-9c83-d3c486b61f7a',
        header: 'name of chatroom',
        reactions: [],
        state: 1,
        mute_status: false,
        follow_status: true,
        attending_status: false,
        is_guest: false,
        is_tagged: false,
        secret_chatroom_left: false,
        member: {
          id: 1260,
          name: 'Sanjay kumar 🤖',
          updated_at: 1675423248,
          is_guest: false,
          user_unique_id: '51c87f56-3cb5-4bc6-8018-3f25118632a4',
          organisation_name: null,
          image_url:
            'https://firebasestorage.googleapis.com/v0/b/collabmates-beta.appspot.com/o/files%2Fprofile%2F1260?alt=media&token=3051d5f4-6bf0-4c11-a320-ded686f6c5bf',
          state: 1,
          is_owner: true,
          member_since_epoch: 1625315057,
          route:
            'route://member_community_profile?community_id=49811&member_id=1260',
          member_since: 'Member since Jul 03 2021',
          custom_intro_text: 'Created this community on 03 Jul 2021',
        },
        images: [],
        pdf: [],
        audios: [],
        videos: [],
        attachments: [],
      },
      community: {
        id: 49811,
        name: 'New Web Test',
        purpose:
          'Hdkhdis djdjd djdjf fjfkf djdjd djdjdjd didjd didkdj djdjdjjd jdjdjdjf',
        image_url:
          'https://firebasestorage.googleapis.com/v0/b/collabmates-beta.appspot.com/o/files%2Fcommunity%2Fimage_community_default?alt=media',
        members_count: 7,
        type: 4,
        sub_type: 39,
        is_paid: true,
        auto_approval: false,
        grace_period: 345600000,
        is_discoverable: false,
        website_url: 'www.google.com',
        community_category: 'With Marketing',
        referral_enabled: false,
        updated_at: 1647680704,
        fee_membership: 5,
        fee_event: 5,
        fee_payment_pages: 5,
        is_whitelabel: false,
        whitelabel_info: null,
        hide_dm_tab: false,
        is_freemium_community: false,
        community_setting_rights: [
          {
            id: 1,
            title: 'Create chat rooms',
            state: 0,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 2,
            title: 'Create polls',
            state: 1,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 3,
            title: 'Create events',
            state: 2,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 4,
            title: 'Respond in chat rooms',
            state: 3,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 6,
            title: 'Auto-approve created chat rooms',
            sub_title:
              "If auto-approved, member's chat rooms will be posted instantly and would not need any approval.",
            state: 5,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 7,
            title: 'Create secret chat rooms',
            state: 6,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 8,
            title: 'Direct messages',
            sub_title:
              'Direct messaging can happen only between a community manager and a community member (not among 2 members).',
            state: 7,
            is_selected: false,
            is_locked: false,
          },
        ],
      },
      is_draft: false,
      unseen_conversation_count: 0,
      last_conversation_time: '07/06/22',
      conversation_users: [],
      member_right_states: [0, 1, 2, 3, 5, 6],
      member_state: 1,
    },
    {
      chatroom: {
        id: 23099,
        title: 'event for 0 cost',
        community_id: 49811,
        answer_text: '',
        share_link: '',
        image_count: 0,
        pdf_count: 0,
        video_count: 0,
        audio_count: 0,
        attachment_count: 1,
        attachments_uploaded: true,
        type: 2,
        date_time: 1648125000000,
        duration: 0,
        is_pending: false,
        answers_count: 0,
        attending_count: 0,
        polls_count: 0,
        card_creation_time: '01:46 PM',
        community_name: 'New Web Test',
        date: '21 Mar 2022',
        created_at: '13:46',
        date_epoch: 1647850619,
        is_secret: false,
        auto_follow_done: false,
        is_edited: false,
        is_paid: true,
        access: 1,
        online_link_type: null,
        online_link_enable_before: 900000,
        is_private: false,
        has_event_recording: false,
        is_private_member: false,
        include_members_later: true,
        has_been_named: true,
        member_id: 1260,
        image_url_round:
          'https://firebasestorage.googleapis.com/v0/b/collabmates-3d601.appspot.com/o/files%2Fmain_website%2Fgeneric_community_banner.png?alt=media&token=044d32ff-3da7-4d8d-9c83-d3c486b61f7a',
        end_date: 1648128600000,
        about: 'new',
        event_payment_link:
          'https://betaweb.likeminds.community/event_pay?event_plan_id=5b4aaf56-6fd2-4b4e-bd5a-649d29c320ca&chatroom_id=23099&community_id=49811',
        header: 'event for 0 cost',
        reactions: [],
        state: 1,
        mute_status: false,
        follow_status: true,
        attending_status: true,
        is_guest: false,
        is_tagged: false,
        secret_chatroom_left: false,
        member: {
          id: 1260,
          name: 'Sanjay kumar 🤖',
          updated_at: 1675423248,
          is_guest: false,
          user_unique_id: '51c87f56-3cb5-4bc6-8018-3f25118632a4',
          organisation_name: null,
          image_url:
            'https://firebasestorage.googleapis.com/v0/b/collabmates-beta.appspot.com/o/files%2Fprofile%2F1260?alt=media&token=3051d5f4-6bf0-4c11-a320-ded686f6c5bf',
          state: 1,
          is_owner: true,
          member_since_epoch: 1625315057,
          route:
            'route://member_community_profile?community_id=49811&member_id=1260',
          member_since: 'Member since Jul 03 2021',
          custom_intro_text: 'Created this community on 03 Jul 2021',
        },
        images: [
          {
            image_url:
              'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/23099/event-23099',
            index: null,
            type: 'image',
          },
        ],
        pdf: [],
        audios: [],
        videos: [],
        attachments: [
          {
            url: 'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/23099/event-23099',
            index: null,
            type: 'image',
          },
        ],
      },
      community: {
        id: 49811,
        name: 'New Web Test',
        purpose:
          'Hdkhdis djdjd djdjf fjfkf djdjd djdjdjd didjd didkdj djdjdjjd jdjdjdjf',
        image_url:
          'https://firebasestorage.googleapis.com/v0/b/collabmates-beta.appspot.com/o/files%2Fcommunity%2Fimage_community_default?alt=media',
        members_count: 7,
        type: 4,
        sub_type: 39,
        is_paid: true,
        auto_approval: false,
        grace_period: 345600000,
        is_discoverable: false,
        website_url: 'www.google.com',
        community_category: 'With Marketing',
        referral_enabled: false,
        updated_at: 1647680704,
        fee_membership: 5,
        fee_event: 5,
        fee_payment_pages: 5,
        is_whitelabel: false,
        whitelabel_info: null,
        hide_dm_tab: false,
        is_freemium_community: false,
        community_setting_rights: [
          {
            id: 1,
            title: 'Create chat rooms',
            state: 0,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 2,
            title: 'Create polls',
            state: 1,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 3,
            title: 'Create events',
            state: 2,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 4,
            title: 'Respond in chat rooms',
            state: 3,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 6,
            title: 'Auto-approve created chat rooms',
            sub_title:
              "If auto-approved, member's chat rooms will be posted instantly and would not need any approval.",
            state: 5,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 7,
            title: 'Create secret chat rooms',
            state: 6,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 8,
            title: 'Direct messages',
            sub_title:
              'Direct messaging can happen only between a community manager and a community member (not among 2 members).',
            state: 7,
            is_selected: false,
            is_locked: false,
          },
        ],
      },
      is_draft: false,
      unseen_conversation_count: 0,
      last_conversation_time: '21/03/22',
      conversation_users: [],
      member_right_states: [0, 1, 2, 3, 5, 6],
      member_state: 1,
    },
    {
      chatroom: {
        id: 23027,
        title: 'lksdlkf sldkfjsl dkfjlskd jf',
        community_id: 49811,
        answer_text: '',
        share_link: '',
        image_count: 0,
        pdf_count: 0,
        video_count: 0,
        audio_count: 0,
        attachment_count: 1,
        attachments_uploaded: true,
        type: 2,
        date_time: 1647520200000,
        duration: 0,
        is_pending: false,
        answers_count: 0,
        attending_count: 0,
        polls_count: 0,
        card_creation_time: '03:49 PM',
        community_name: 'New Web Test',
        date: '16 Mar 2022',
        created_at: '15:49',
        date_epoch: 1647425977,
        is_secret: false,
        auto_follow_done: false,
        is_edited: false,
        is_paid: true,
        access: 2,
        online_link_type: null,
        online_link_enable_before: 900000,
        is_private: false,
        has_event_recording: false,
        is_private_member: false,
        include_members_later: true,
        has_been_named: true,
        member_id: 1260,
        image_url_round:
          'https://firebasestorage.googleapis.com/v0/b/collabmates-3d601.appspot.com/o/files%2Fmain_website%2Fgeneric_community_banner.png?alt=media&token=044d32ff-3da7-4d8d-9c83-d3c486b61f7a',
        end_date: 1647523800000,
        about: 'lkjd lkfjsldkfjlsdkfj',
        webflow_item_id: '6231b9ba81694a8c890ca328',
        event_payment_link:
          'https://betaweb.likeminds.community/event_pay?event_plan_id=f17647e7-6859-4f36-9f36-8ccbdd686650&chatroom_id=23027&community_id=49811',
        event_web_page:
          'http://subscription-model.webflow.io/events/lksdlkf-sldkfjsl-dkfjlskd-jf',
        header: 'lksdlkf sldkfjsl dkfjlskd jf',
        reactions: [],
        state: 1,
        mute_status: false,
        follow_status: true,
        attending_status: true,
        is_guest: false,
        is_tagged: false,
        secret_chatroom_left: false,
        member: {
          id: 1260,
          name: 'Sanjay kumar 🤖',
          updated_at: 1675423248,
          is_guest: false,
          user_unique_id: '51c87f56-3cb5-4bc6-8018-3f25118632a4',
          organisation_name: null,
          image_url:
            'https://firebasestorage.googleapis.com/v0/b/collabmates-beta.appspot.com/o/files%2Fprofile%2F1260?alt=media&token=3051d5f4-6bf0-4c11-a320-ded686f6c5bf',
          state: 1,
          is_owner: true,
          member_since_epoch: 1625315057,
          route:
            'route://member_community_profile?community_id=49811&member_id=1260',
          member_since: 'Member since Jul 03 2021',
          custom_intro_text: 'Created this community on 03 Jul 2021',
        },
        images: [
          {
            image_url:
              'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/23027/event-23027',
            index: null,
            type: 'image',
          },
        ],
        pdf: [],
        audios: [],
        videos: [],
        attachments: [
          {
            url: 'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/23027/event-23027',
            index: null,
            type: 'image',
          },
        ],
      },
      community: {
        id: 49811,
        name: 'New Web Test',
        purpose:
          'Hdkhdis djdjd djdjf fjfkf djdjd djdjdjd didjd didkdj djdjdjjd jdjdjdjf',
        image_url:
          'https://firebasestorage.googleapis.com/v0/b/collabmates-beta.appspot.com/o/files%2Fcommunity%2Fimage_community_default?alt=media',
        members_count: 7,
        type: 4,
        sub_type: 39,
        is_paid: true,
        auto_approval: false,
        grace_period: 345600000,
        is_discoverable: false,
        website_url: 'www.google.com',
        community_category: 'With Marketing',
        referral_enabled: false,
        updated_at: 1647680704,
        fee_membership: 5,
        fee_event: 5,
        fee_payment_pages: 5,
        is_whitelabel: false,
        whitelabel_info: null,
        hide_dm_tab: false,
        is_freemium_community: false,
        community_setting_rights: [
          {
            id: 1,
            title: 'Create chat rooms',
            state: 0,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 2,
            title: 'Create polls',
            state: 1,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 3,
            title: 'Create events',
            state: 2,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 4,
            title: 'Respond in chat rooms',
            state: 3,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 6,
            title: 'Auto-approve created chat rooms',
            sub_title:
              "If auto-approved, member's chat rooms will be posted instantly and would not need any approval.",
            state: 5,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 7,
            title: 'Create secret chat rooms',
            state: 6,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 8,
            title: 'Direct messages',
            sub_title:
              'Direct messaging can happen only between a community manager and a community member (not among 2 members).',
            state: 7,
            is_selected: false,
            is_locked: false,
          },
        ],
      },
      is_draft: false,
      unseen_conversation_count: 0,
      last_conversation_time: '16/03/22',
      conversation_users: [],
      member_right_states: [0, 1, 2, 3, 5, 6],
      member_state: 1,
    },
    {
      chatroom: {
        id: 22961,
        title: 'event banner image test',
        community_id: 49811,
        answer_text: '',
        share_link: '',
        image_count: 0,
        pdf_count: 0,
        video_count: 0,
        audio_count: 0,
        attachment_count: 1,
        attachments_uploaded: true,
        type: 2,
        date_time: 1646915400000,
        duration: 0,
        is_pending: false,
        answers_count: 0,
        attending_count: 0,
        polls_count: 0,
        card_creation_time: '12:46 PM',
        community_name: 'New Web Test',
        date: '10 Mar 2022',
        created_at: '12:46',
        date_epoch: 1646896579,
        is_secret: false,
        auto_follow_done: false,
        is_edited: false,
        is_paid: false,
        access: 1,
        online_link_type: null,
        online_link_enable_before: 900000,
        is_private: false,
        has_event_recording: false,
        is_private_member: false,
        include_members_later: true,
        has_been_named: true,
        member_id: 1260,
        image_url_round:
          'https://firebasestorage.googleapis.com/v0/b/collabmates-3d601.appspot.com/o/files%2Fmain_website%2Fgeneric_community_banner.png?alt=media&token=044d32ff-3da7-4d8d-9c83-d3c486b61f7a',
        end_date: 1646919000000,
        about: 'kdfjslkdfj slkdfjlskjf',
        header: 'event banner image test',
        reactions: [],
        state: 1,
        mute_status: false,
        follow_status: true,
        attending_status: true,
        is_guest: false,
        is_tagged: false,
        secret_chatroom_left: false,
        member: {
          id: 1260,
          name: 'Sanjay kumar 🤖',
          updated_at: 1675423248,
          is_guest: false,
          user_unique_id: '51c87f56-3cb5-4bc6-8018-3f25118632a4',
          organisation_name: null,
          image_url:
            'https://firebasestorage.googleapis.com/v0/b/collabmates-beta.appspot.com/o/files%2Fprofile%2F1260?alt=media&token=3051d5f4-6bf0-4c11-a320-ded686f6c5bf',
          state: 1,
          is_owner: true,
          member_since_epoch: 1625315057,
          route:
            'route://member_community_profile?community_id=49811&member_id=1260',
          member_since: 'Member since Jul 03 2021',
          custom_intro_text: 'Created this community on 03 Jul 2021',
        },
        images: [
          {
            image_url:
              'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/22961/event-22961',
            index: null,
            type: 'image',
          },
        ],
        pdf: [],
        audios: [],
        videos: [],
        attachments: [
          {
            url: 'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/collabcard/22961/event-22961',
            index: null,
            type: 'image',
          },
        ],
      },
      community: {
        id: 49811,
        name: 'New Web Test',
        purpose:
          'Hdkhdis djdjd djdjf fjfkf djdjd djdjdjd didjd didkdj djdjdjjd jdjdjdjf',
        image_url:
          'https://firebasestorage.googleapis.com/v0/b/collabmates-beta.appspot.com/o/files%2Fcommunity%2Fimage_community_default?alt=media',
        members_count: 7,
        type: 4,
        sub_type: 39,
        is_paid: true,
        auto_approval: false,
        grace_period: 345600000,
        is_discoverable: false,
        website_url: 'www.google.com',
        community_category: 'With Marketing',
        referral_enabled: false,
        updated_at: 1647680704,
        fee_membership: 5,
        fee_event: 5,
        fee_payment_pages: 5,
        is_whitelabel: false,
        whitelabel_info: null,
        hide_dm_tab: false,
        is_freemium_community: false,
        community_setting_rights: [
          {
            id: 1,
            title: 'Create chat rooms',
            state: 0,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 2,
            title: 'Create polls',
            state: 1,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 3,
            title: 'Create events',
            state: 2,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 4,
            title: 'Respond in chat rooms',
            state: 3,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 6,
            title: 'Auto-approve created chat rooms',
            sub_title:
              "If auto-approved, member's chat rooms will be posted instantly and would not need any approval.",
            state: 5,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 7,
            title: 'Create secret chat rooms',
            state: 6,
            is_selected: true,
            is_locked: false,
          },
          {
            id: 8,
            title: 'Direct messages',
            sub_title:
              'Direct messaging can happen only between a community manager and a community member (not among 2 members).',
            state: 7,
            is_selected: false,
            is_locked: false,
          },
        ],
      },
      is_draft: false,
      unseen_conversation_count: 0,
      last_conversation_time: '10/03/22',
      conversation_users: [],
      member_right_states: [0, 1, 2, 3, 5, 6],
      member_state: 1,
    },
  ],
  total_pages: 14,
  total_unseen_count: 0,
};
