export const obj = {
  success: true,
  data: {
    chatrooms: [
      {
        access: null,
        access_without_subscription: false,
        answer_text: '',
        answers_count: 0,
        attachment_count: 0,
        attachments_uploaded: false,
        attended: false,
        attending_count: 0,
        attending_status: false,
        audio_count: 0,
        auto_follow_done: false,
        card_creation_time: '03:11 PM',
        chat_request_created_at: null,
        chat_request_state: null,
        chat_requested_by: null,
        cohorts: [],
        community_id: 50421,
        community_name: 'Notification settings',
        created_at: '15:11',
        date: '17 Aug 2022',
        date_epoch: 1660729282,
        date_time: 0,
        duration: 0,
        external_seen: true,
        follow_status: true,
        header: 'Announcement Room 📣',
        id: 27845,
        image_count: 0,
        include_members_later: true,
        is_edited: false,
        is_guest: false,
        is_paid: false,
        is_pending: false,
        is_pinned: true,
        is_private: false,
        is_private_member: false,
        is_secret: false,
        is_tagged: false,
        last_response_members: [
          {
            chatroom_id: 27845,
            community_id: 50421,
            created_at: 1661262431,
            custom_title: 'Community Manager',
            id: 3563,
            image_url: '',
            is_guest: false,
            is_owner: false,
            member_since: 'Member since Aug 23 2022',
            name: 'Ankit Garg SDK',
            route:
              'route://member_community_profile?community_id=50421&member_id=3563',
            state: 1,
            user_unique_id: '53208f29-5d15-473e-ab70-5fd77605be0f',
          },
        ],
        member: {
          community_id: 50421,
          created_at: 1660729281,
          custom_title: 'Owner',
          id: 3547,
          image_url: '',
          is_guest: false,
          is_owner: true,
          member_since: 'Member since Aug 17 2022',
          name: 'Notification settings bot',
          route:
            'route://member_community_profile?community_id=50421&member_id=3547',
          state: 1,
          user_unique_id: '53f5f457-70e3-4f07-9fb9-078b12f36510',
        },
        member_can_message: false,
        mute_status: false,
        online_link_enable_before: 900000,
        online_link_type: null,
        participants_count: 47,
        pdf_count: 0,
        polls_count: 0,
        reactions: [],
        share_link: '',
        state: 1,
        third_party_unique_id: null,
        title: 'We will send all the announcements here on this chatroom.',
        total_response_count: 4,
        type: 7,
        video_count: 0,
      },
      {
        access: null,
        access_without_subscription: false,
        answer_text: '',
        answers_count: 0,
        attachment_count: 0,
        attachments_uploaded: false,
        attended: false,
        attending_count: 0,
        attending_status: false,
        audio_count: 0,
        auto_follow_done: false,
        card_creation_time: '08:42 AM',
        chat_request_created_at: null,
        chat_request_state: null,
        chat_requested_by: null,
        chatroom_image_url:
          'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/chatroom/image/1674616339876',
        co_hosts: [],
        cohorts: [],
        community_id: 50421,
        community_name: 'Notification settings',
        created_at: '08:42',
        date: '25 Jan 2023',
        date_epoch: 1674616373,
        date_time: 0,
        duration: 0,
        external_seen: true,
        follow_status: false,
        header: 'CR1',
        id: 71852,
        image_count: 0,
        include_members_later: false,
        is_edited: false,
        is_guest: false,
        is_paid: false,
        is_pending: false,
        is_pinned: false,
        is_private: false,
        is_private_member: false,
        is_secret: false,
        is_tagged: false,
        member: {
          community_id: 50421,
          created_at: 1660729281,
          custom_title: 'Owner',
          id: 3547,
          image_url: '',
          is_guest: false,
          is_owner: true,
          member_since: 'Member since Aug 17 2022',
          name: 'Notification settings bot',
          route:
            'route://member_community_profile?community_id=50421&member_id=3547',
          state: 1,
          user_unique_id: '53f5f457-70e3-4f07-9fb9-078b12f36510',
        },
        member_can_message: true,
        mute_status: false,
        online_link_enable_before: 900000,
        online_link_type: null,
        participants_count: 4,
        pdf_count: 0,
        polls_count: 0,
        reactions: [],
        share_link: '',
        state: 1,
        third_party_unique_id: '',
        title: '2',
        total_response_count: 0,
        type: 0,
        video_count: 0,
      },
      {
        access: null,
        access_without_subscription: false,
        answer_text: '',
        answers_count: 0,
        attachment_count: 0,
        attachments_uploaded: false,
        attended: false,
        attending_count: 0,
        attending_status: false,
        audio_count: 0,
        auto_follow_done: false,
        card_creation_time: '10:12 PM',
        chat_request_created_at: null,
        chat_request_state: null,
        chat_requested_by: null,
        chatroom_image_url:
          'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/chatroom/image/1674578515137',
        co_hosts: [],
        cohorts: [],
        community_id: 50421,
        community_name: 'Notification settings',
        created_at: '22:12',
        date: '24 Jan 2023',
        date_epoch: 1674578529,
        date_time: 0,
        duration: 0,
        external_seen: true,
        follow_status: false,
        header: 'NC3',
        id: 71847,
        image_count: 0,
        include_members_later: false,
        is_edited: false,
        is_guest: false,
        is_paid: false,
        is_pending: false,
        is_pinned: false,
        is_private: false,
        is_private_member: false,
        is_secret: false,
        is_tagged: false,
        member: {
          community_id: 50421,
          created_at: 1660729281,
          custom_title: 'Owner',
          id: 3547,
          image_url: '',
          is_guest: false,
          is_owner: true,
          member_since: 'Member since Aug 17 2022',
          name: 'Notification settings bot',
          route:
            'route://member_community_profile?community_id=50421&member_id=3547',
          state: 1,
          user_unique_id: '53f5f457-70e3-4f07-9fb9-078b12f36510',
        },
        member_can_message: true,
        mute_status: false,
        online_link_enable_before: 900000,
        online_link_type: null,
        participants_count: 4,
        pdf_count: 0,
        polls_count: 0,
        reactions: [],
        share_link: '',
        state: 1,
        third_party_unique_id: '',
        title: 'cd',
        total_response_count: 0,
        type: 0,
        video_count: 0,
      },
      {
        access: null,
        access_without_subscription: false,
        answer_text: '',
        answers_count: 0,
        attachment_count: 0,
        attachments_uploaded: false,
        attended: false,
        attending_count: 0,
        attending_status: false,
        audio_count: 0,
        auto_follow_done: true,
        card_creation_time: '07:19 PM',
        chat_request_created_at: null,
        chat_request_state: null,
        chat_requested_by: null,
        chatroom_image_url:
          'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/chatroom/image/1671889773717',
        co_hosts: [],
        cohorts: [],
        community_id: 50421,
        community_name: 'Notification settings',
        created_at: '19:19',
        date: '24 Dec 2022',
        date_epoch: 1671889777,
        date_time: 0,
        duration: 0,
        external_seen: true,
        follow_status: true,
        header: 'Testing chatroom 2233',
        id: 69285,
        image_count: 0,
        include_members_later: true,
        is_edited: false,
        is_guest: false,
        is_paid: false,
        is_pending: false,
        is_pinned: false,
        is_private: false,
        is_private_member: false,
        is_secret: false,
        is_tagged: false,
        member: {
          community_id: 50421,
          created_at: 1660729281,
          custom_title: 'Owner',
          id: 3547,
          image_url: '',
          is_guest: false,
          is_owner: true,
          member_since: 'Member since Aug 17 2022',
          name: 'Notification settings bot',
          route:
            'route://member_community_profile?community_id=50421&member_id=3547',
          state: 1,
          user_unique_id: '53f5f457-70e3-4f07-9fb9-078b12f36510',
        },
        member_can_message: true,
        mute_status: false,
        online_link_enable_before: 900000,
        online_link_type: null,
        participants_count: 31,
        pdf_count: 0,
        polls_count: 0,
        reactions: [],
        share_link: '',
        state: 1,
        third_party_unique_id: '',
        title: 'NNS',
        total_response_count: 0,
        type: 0,
        video_count: 0,
      },
      {
        access: null,
        access_without_subscription: false,
        answer_text: '',
        answers_count: 0,
        attachment_count: 0,
        attachments_uploaded: false,
        attended: false,
        attending_count: 0,
        attending_status: false,
        audio_count: 0,
        auto_follow_done: false,
        card_creation_time: '12:08 PM',
        chat_request_created_at: null,
        chat_request_state: null,
        chat_requested_by: null,
        chatroom_image_url:
          'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/chatroom/image/1667025474623',
        co_hosts: [],
        cohorts: [],
        community_id: 50421,
        community_name: 'Notification settings',
        created_at: '12:08',
        date: '29 Oct 2022',
        date_epoch: 1667025480,
        date_time: 0,
        duration: 0,
        external_seen: true,
        follow_status: false,
        header: 'Noti Set',
        id: 29038,
        image_count: 0,
        include_members_later: false,
        is_edited: false,
        is_guest: false,
        is_paid: false,
        is_pending: false,
        is_pinned: false,
        is_private: false,
        is_private_member: false,
        is_secret: false,
        is_tagged: false,
        last_response_members: [
          {
            chatroom_id: 29038,
            community_id: 50421,
            created_at: 1668097978,
            custom_title: 'Community Manager',
            id: 3772,
            image_url:
              'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/profile/1670748419352',
            is_guest: false,
            is_owner: false,
            member_since: 'Member since Nov 10 2022',
            name: 'Himanshu 2',
            route:
              'route://member_community_profile?community_id=50421&member_id=3772',
            state: 1,
            user_unique_id: 'ec62aa18-5ffb-482e-bb24-339a7e09c3be',
          },
        ],
        member: {
          community_id: 50421,
          created_at: 1660729281,
          custom_title: 'Owner',
          id: 3547,
          image_url: '',
          is_guest: false,
          is_owner: true,
          member_since: 'Member since Aug 17 2022',
          name: 'Notification settings bot',
          route:
            'route://member_community_profile?community_id=50421&member_id=3547',
          state: 1,
          user_unique_id: '53f5f457-70e3-4f07-9fb9-078b12f36510',
        },
        member_can_message: true,
        mute_status: false,
        online_link_enable_before: 900000,
        online_link_type: null,
        participants_count: 9,
        pdf_count: 0,
        polls_count: 0,
        reactions: [],
        share_link: '',
        state: 1,
        third_party_unique_id: '',
        title: 'NOTI SET',
        total_response_count: 80,
        type: 0,
        video_count: 0,
      },
      {
        access: null,
        access_without_subscription: false,
        answer_text: '',
        answers_count: 0,
        attachment_count: 0,
        attachments_uploaded: false,
        attended: false,
        attending_count: 0,
        attending_status: false,
        audio_count: 0,
        auto_follow_done: false,
        card_creation_time: '08:01 PM',
        chat_request_created_at: null,
        chat_request_state: null,
        chat_requested_by: null,
        chatroom_image_url:
          'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/chatroom/image/1666276298114',
        co_hosts: [],
        cohorts: [],
        community_id: 50421,
        community_name: 'Notification settings',
        created_at: '20:01',
        date: '20 Oct 2022',
        date_epoch: 1666276302,
        date_time: 0,
        duration: 0,
        external_seen: true,
        follow_status: false,
        header: 'NC11',
        id: 28552,
        image_count: 0,
        include_members_later: false,
        is_edited: false,
        is_guest: false,
        is_paid: false,
        is_pending: false,
        is_pinned: false,
        is_private: false,
        is_private_member: false,
        is_secret: false,
        is_tagged: false,
        last_response_members: [],
        member: {
          community_id: 50421,
          created_at: 1660729281,
          custom_title: 'Owner',
          id: 3547,
          image_url: '',
          is_guest: false,
          is_owner: true,
          member_since: 'Member since Aug 17 2022',
          name: 'Notification settings bot',
          route:
            'route://member_community_profile?community_id=50421&member_id=3547',
          state: 1,
          user_unique_id: '53f5f457-70e3-4f07-9fb9-078b12f36510',
        },
        member_can_message: true,
        mute_status: false,
        online_link_enable_before: 900000,
        online_link_type: null,
        participants_count: 11,
        pdf_count: 0,
        polls_count: 0,
        reactions: [],
        share_link: '',
        state: 1,
        third_party_unique_id: '',
        title: 'NC11',
        total_response_count: 73,
        type: 0,
        video_count: 0,
      },
      {
        access: null,
        access_without_subscription: false,
        answer_text: '',
        answers_count: 0,
        attachment_count: 0,
        attachments_uploaded: false,
        attended: false,
        attending_count: 0,
        attending_status: false,
        audio_count: 0,
        auto_follow_done: false,
        card_creation_time: '08:01 PM',
        chat_request_created_at: null,
        chat_request_state: null,
        chat_requested_by: null,
        chatroom_image_url:
          'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/chatroom/image/1666276261876',
        co_hosts: [],
        cohorts: [],
        community_id: 50421,
        community_name: 'Notification settings',
        created_at: '20:01',
        date: '20 Oct 2022',
        date_epoch: 1666276267,
        date_time: 0,
        duration: 0,
        external_seen: true,
        follow_status: false,
        header: 'NC10',
        id: 28551,
        image_count: 0,
        include_members_later: false,
        is_edited: false,
        is_guest: false,
        is_paid: false,
        is_pending: false,
        is_pinned: false,
        is_private: false,
        is_private_member: false,
        is_secret: false,
        is_tagged: false,
        last_response_members: [],
        member: {
          community_id: 50421,
          created_at: 1660729281,
          custom_title: 'Owner',
          id: 3547,
          image_url: '',
          is_guest: false,
          is_owner: true,
          member_since: 'Member since Aug 17 2022',
          name: 'Notification settings bot',
          route:
            'route://member_community_profile?community_id=50421&member_id=3547',
          state: 1,
          user_unique_id: '53f5f457-70e3-4f07-9fb9-078b12f36510',
        },
        member_can_message: true,
        mute_status: false,
        online_link_enable_before: 900000,
        online_link_type: null,
        participants_count: 8,
        pdf_count: 0,
        polls_count: 0,
        reactions: [],
        share_link: '',
        state: 1,
        third_party_unique_id: '',
        title: 'NC10',
        total_response_count: 4,
        type: 0,
        video_count: 0,
      },
      {
        access: null,
        access_without_subscription: false,
        answer_text: '',
        answers_count: 0,
        attachment_count: 0,
        attachments_uploaded: false,
        attended: false,
        attending_count: 0,
        attending_status: false,
        audio_count: 0,
        auto_follow_done: false,
        card_creation_time: '07:59 PM',
        chat_request_created_at: null,
        chat_request_state: null,
        chat_requested_by: null,
        chatroom_image_url:
          'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/chatroom/image/1666276138950',
        co_hosts: [],
        cohorts: [],
        community_id: 50421,
        community_name: 'Notification settings',
        created_at: '19:59',
        date: '20 Oct 2022',
        date_epoch: 1666276143,
        date_time: 0,
        duration: 0,
        external_seen: true,
        follow_status: false,
        header: 'NC8',
        id: 28550,
        image_count: 0,
        include_members_later: false,
        is_edited: false,
        is_guest: false,
        is_paid: false,
        is_pending: false,
        is_pinned: false,
        is_private: false,
        is_private_member: false,
        is_secret: false,
        is_tagged: false,
        last_response_members: [
          {
            chatroom_id: 28550,
            community_id: 50421,
            created_at: 1670395292,
            id: 3895,
            image_url: '',
            is_guest: false,
            is_owner: false,
            member_since: 'Member since Dec 07 2022',
            name: 'sanjay',
            route:
              'route://member_community_profile?community_id=50421&member_id=3895',
            state: 4,
            user_unique_id: '78cb8da7-bade-4d34-afb8-91c8e151e212',
          },
        ],
        member: {
          community_id: 50421,
          created_at: 1660729281,
          custom_title: 'Owner',
          id: 3547,
          image_url: '',
          is_guest: false,
          is_owner: true,
          member_since: 'Member since Aug 17 2022',
          name: 'Notification settings bot',
          route:
            'route://member_community_profile?community_id=50421&member_id=3547',
          state: 1,
          user_unique_id: '53f5f457-70e3-4f07-9fb9-078b12f36510',
        },
        member_can_message: true,
        mute_status: false,
        online_link_enable_before: 900000,
        online_link_type: null,
        participants_count: 9,
        pdf_count: 0,
        polls_count: 0,
        reactions: [],
        share_link: '',
        state: 1,
        third_party_unique_id: '',
        title: 'NC8',
        total_response_count: 5,
        type: 0,
        video_count: 0,
      },
      {
        access: null,
        access_without_subscription: false,
        answer_text: '',
        answers_count: 0,
        attachment_count: 0,
        attachments_uploaded: false,
        attended: false,
        attending_count: 0,
        attending_status: false,
        audio_count: 0,
        auto_follow_done: false,
        card_creation_time: '07:58 PM',
        chat_request_created_at: null,
        chat_request_state: null,
        chat_requested_by: null,
        chatroom_image_url:
          'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/chatroom/image/1666276097358',
        co_hosts: [],
        cohorts: [],
        community_id: 50421,
        community_name: 'Notification settings',
        created_at: '19:58',
        date: '20 Oct 2022',
        date_epoch: 1666276102,
        date_time: 0,
        duration: 0,
        external_seen: true,
        follow_status: false,
        header: 'NC6',
        id: 28549,
        image_count: 0,
        include_members_later: false,
        is_edited: false,
        is_guest: false,
        is_paid: false,
        is_pending: false,
        is_pinned: false,
        is_private: false,
        is_private_member: false,
        is_secret: false,
        is_tagged: false,
        last_response_members: [],
        member: {
          community_id: 50421,
          created_at: 1660729281,
          custom_title: 'Owner',
          id: 3547,
          image_url: '',
          is_guest: false,
          is_owner: true,
          member_since: 'Member since Aug 17 2022',
          name: 'Notification settings bot',
          route:
            'route://member_community_profile?community_id=50421&member_id=3547',
          state: 1,
          user_unique_id: '53f5f457-70e3-4f07-9fb9-078b12f36510',
        },
        member_can_message: true,
        mute_status: false,
        online_link_enable_before: 900000,
        online_link_type: null,
        participants_count: 8,
        pdf_count: 0,
        polls_count: 0,
        reactions: [],
        share_link: '',
        state: 1,
        third_party_unique_id: '',
        title: 'NC6',
        total_response_count: 1,
        type: 0,
        video_count: 0,
      },
      {
        access: null,
        access_without_subscription: false,
        answer_text: '',
        answers_count: 0,
        attachment_count: 0,
        attachments_uploaded: false,
        attended: false,
        attending_count: 0,
        attending_status: false,
        audio_count: 0,
        auto_follow_done: false,
        card_creation_time: '07:57 PM',
        chat_request_created_at: null,
        chat_request_state: null,
        chat_requested_by: null,
        chatroom_image_url:
          'https://beta-likeminds-media.s3.ap-south-1.amazonaws.com/files/chatroom/image/1666276068635',
        co_hosts: [],
        cohorts: [],
        community_id: 50421,
        community_name: 'Notification settings',
        created_at: '19:57',
        date: '20 Oct 2022',
        date_epoch: 1666276073,
        date_time: 0,
        duration: 0,
        external_seen: true,
        follow_status: false,
        header: 'NC5',
        id: 28548,
        image_count: 0,
        include_members_later: false,
        is_edited: false,
        is_guest: false,
        is_paid: false,
        is_pending: false,
        is_pinned: false,
        is_private: false,
        is_private_member: false,
        is_secret: false,
        is_tagged: false,
        member: {
          community_id: 50421,
          created_at: 1660729281,
          custom_title: 'Owner',
          id: 3547,
          image_url: '',
          is_guest: false,
          is_owner: true,
          member_since: 'Member since Aug 17 2022',
          name: 'Notification settings bot',
          route:
            'route://member_community_profile?community_id=50421&member_id=3547',
          state: 1,
          user_unique_id: '53f5f457-70e3-4f07-9fb9-078b12f36510',
        },
        member_can_message: true,
        mute_status: false,
        online_link_enable_before: 900000,
        online_link_type: null,
        participants_count: 5,
        pdf_count: 0,
        polls_count: 0,
        reactions: [],
        share_link: '',
        state: 1,
        third_party_unique_id: '',
        title: 'NC5',
        total_response_count: 0,
        type: 0,
        video_count: 0,
      },
    ],
    pinned_chatrooms_count: 1,
  },
};
